### ISSUE TITLE
Melhorar página de perfil

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#10]
Atualmente a página de "perfil" (http://demo.timtec.com.br/profile) não mostra algumas informações. Acrescentar:
1. [x] Visualização de campo de estado, cidade, ocupação, redes sociais e site (basicamente mostrar os campos que estão no cadastro)
2. [x] Acrescentar visualização "cursos em andamento" na mesma página (a página meus cursos pode ser mantida, mas é necessário que cursos em andamento apareça na página do perfil também)
3. [ ] Acrescentar, ao lado de cada curso em andamento" botão para " ver anotações do curso"

**Comment by moacirmoda** [comment]
> Acrescentar, ao lado de cada curso em andamento" botão para " ver anotações do curso"

@robertkapa estas anotações hoje em dia não são públicas. A intenção é disponibilizá-las publicamente?

**Comment by intrepidocabral** [comment]
> @robertkapa estas anotações hoje em dia não são públicas. A intenção é disponibilizá-las publicamente?

Não. As anotações são privadas.

**Comment by moacirmoda** [comment]
Em reunião, eu e @robertkapa decidimos por não incluir um botão para as anotações do usuário.
