### ISSUE TITLE
BUG: user admin quebrado

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#100]
Por algum motivo ao qual não fazemos a menor ideia, existe 1 usuário administrador na plataforma que está vendo a ferramenta bem mais quebrada do que os demais users admins. 

Este user é o associado ao email natalia@lfdb.com.br. Por algum motivo esse user não entra no perfil. 

Comportamento esperado de um user admin: https://youtu.be/eEuRK1Y4naM

Comportamento encontrado pós-instalação da versão v4. Bug quando o usuário tenta ver o perfil: https://youtu.be/UuBjzJuQl18

Esse mesmo usuário, diferente de outros admins, não consegue acessar a página "meus certificados" mesmo tendo concluido vários cursos:

![selecao_017](https://cloud.githubusercontent.com/assets/641411/24372294/dd09a27c-1303-11e7-9538-473b5241d902.png)

**Comment by moacirmoda** [comment]
Não consegui simular o erro:

![image](https://cloud.githubusercontent.com/assets/549428/24470798/88748742-1496-11e7-8a01-9a8cc95cc66b.png)


![image](https://cloud.githubusercontent.com/assets/549428/24470806/8c44ce0e-1496-11e7-951e-a30edb5be109.png)

**Comment by Nathlis** [comment]
Realmente agora meu perfil está carregando:

![tim tec](https://cloud.githubusercontent.com/assets/18741130/24471233/dad264e0-1497-11e7-9acb-626cac3339dc.png)

Porém ainda não consigo ver meus comprovantes:
![tim tec_2](https://cloud.githubusercontent.com/assets/18741130/24471246/e7c53b6e-1497-11e7-85c1-9edb065917a8.png)

Também não aparece o botão de comprovantes:
![tim tec_3](https://cloud.githubusercontent.com/assets/18741130/24471335/2f6e595a-1498-11e7-8ff6-32c37e6f4ec3.png)

E também não carrega meu comprovante indo pela página do perfil:
![tim tec_4](https://cloud.githubusercontent.com/assets/18741130/24471372/4d72b40a-1498-11e7-9e64-43bbc6cde98b.png)

**Comment by moacirmoda** [comment]
@Nathlis em qual instância vc tá mexendo? aqui clico e aparece normal.

**Comment by Nathlis** [comment]
Desculpa @moacirmoda acabei testando no mooc atual. Realmente no ambiente de teste está funcionando normalmente.
