### ISSUE TITLE
Bug de criação de novos cursos

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#101]
Quando um usuário tenta criar um novo curso, ao adicionar um novo vídeo, a engine não salva (ou pelo menos não mostra a mensagem de sucesso de que o vídeo foi salvo) pelo botão "salvar". 

Fizemos testes com vários usuários e preenchemos  todos os campos para adicionar um vídeo de diversas formas, mas está apresentando erro.

Comportamento com bug: https://youtu.be/8f4XZ1-Oprg

O curioso é que ao adicionar novos vídeos em unidades/cursos já existentes o sistema não apresenta problema, mas ao tentar adicionar vídeos novos, a interface parece não funcionar adequadamente. Reparei que se clico em "publicar", aparece a mensagem de que está salvo (????).

**Comment by moacirmoda** [comment]
Idem ao #105.

**Comment by moacirmoda** [comment]
Se basear no código: https://github.com/hacklabr/timtec/blob/paralapraca/administration/serializer.py

**Comment by moacirmoda** [comment]
Aparentemente resolvido. Favor testar.

**Comment by robertkapa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Novo deploy TIM Tec - V 4.0](https://trello.com/c/2VCTgimB/45-novo-deploy-tim-tec-v-4-0)

**Comment by intrepidocabral** [comment]
**Fiz os testes, não funciona.** A criação de um novo curso do zero não se completa. E além de não conseguir criar o curso, o sistema não dá nenhum aviso de qual é o problema. Simplesmente não salva. 

Teste com ambiente de update, tema timtec(http://li1109-208.members.linode.com): https://youtu.be/XbgacWsO81M

Teste com ambiente de deploy do zero, tema if (http://if.dev.timtec.com.br):  https://youtu.be/pDrIOI3x0Y8

**Comment by moacirmoda** [comment]
@robertkapa não consegui simular o erro. Aqui corre tudo normalmente.
Veja o curso que criei: 
- Chrome: http://li1109-208.members.linode.com/admin/courses/50/
- Firefox: http://li1109-208.members.linode.com/admin/courses/51/

Será que não é pq as imagens que vc tenta subir são muito grandes?
Abra o console e reporte pra mim os erros e warnings que são levantados, veja também a aba Network, se os requests estão retornando responses.

**Comment by intrepidocabral** [comment]
@moacirmoda tenta publicar esses cursos que vc criou. Não da certo, só fica em modo rascunho. 

Tenta colocar um vídeo do youtube e preencher todos os campos.

**Comment by moacirmoda** [comment]
Consegui publicar ambos.

**Comment by moacirmoda** [comment]
Eu estou sem software para gravar tela e a internet onde estou está limitada.
Acho mais vantagem você debugar ai e entender se trata-se de um erro ou de lentidão nos requests do angular.

**Comment by intrepidocabral** [comment]
**Fiz o teste de novo: quando vc adiciona thumbnail e homethumbnail não mostra mensagem de sucesso/insucesso.** De uma olhada nisso, colocar uma imagem de teste nos dois campos e tenta salvar. 

Sobre o rascunho/público: está funcionando sim, testei com afinco e vi. Tem que apertar 2 vezes, mas funciona. Sorry! Thanks. 

Acho que o problema é realmente quando coloca os thumbnails.

**Comment by moacirmoda** [comment]
Testei de novo e tudo correndo normal aqui, Felipe.
Imagino que o problema seja sua conexão mesmo. Tanto que isso se reflete no momento de salvar de rascunho/público:
> Tem que apertar 2 vezes, mas funciona.

**Comment by intrepidocabral** [comment]
> Testei de novo e tudo correndo normal aqui, Felipe.
Imagino que o problema seja sua conexão mesmo. Tanto que isso se reflete no momento de salvar de rascunho/público.


Por favor, faça o seguinte teste: coloque uma imagem no thumbnail e outra no homethumbnail e tente salvar o curso. Repare que não vai aparecer a mensagem de sucesso em verde. Faça isso nesse ambiente: http://li1109-208.members.linode.com

**Comment by intrepidocabral** [comment]
@moacirmoda fizemos o teste com tema do institutot tim no ambiente que estava na tag v3.3 e que foi feito update para v4.1. Colocamos uma imagem no thumbnail e outra no homethumbnail e tentamos salvar o curso. Repare que não vai aparecer a mensagem de sucesso em verde. Faça isso nesse ambiente: http://li1109-208.members.linode.com e verá.

**Comment by moacirmoda** [comment]
Refiz o teste e correu tudo corretamente (com uma pequena lentidão, porém,
ocorreu).

**Comment by moacirmoda** [comment]
felipe, este é exatamente o teste que fiz.
Segue vídeo: https://youtu.be/9qIs7v-SjHA

**Comment by intrepidocabral** [comment]
ok! parece estar lento, mas funcionando. Valeu.
