### ISSUE TITLE
bug: layout da página home dos cursos

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#102]
Este problema é um pouco complexo de explicar, mas vamos tentar sintetizar. 

Antes era assim:
* Unidades de cursos baseadas em vídeo aulas do youtube;
* Engine do front pegava um thumb do vídeo e mostrava uma miniatura de um frame na home; 

Depois:
* Unidades de cursos baseadas em vídeos, texto/imagem ou atividades;
* Engine do front na home do curso não tem imagem para apresentar no caso de uma unidade ser composta apenas de texto/imagem

Carrencia: uma unidade deve possuir um campo de thumbnail, assim como na home centro (video introdutorio), para que seja possível aparecer no front da home de um cursos as miniaturas de imagem relativas a unidade. 

Exemplo do problema: 
![curso- teste](https://cloud.githubusercontent.com/assets/641411/24374050/db46821a-1309-11e7-998a-b8adae4e633e.png)

**Comment by moacirmoda** [comment]
Na realidade isto não é um bug, e sim uma especificação incompleta.

Adicionei um novo campo Thumbnail, baseando-me nos outros campos de imagem do sistema:
![image](https://cloud.githubusercontent.com/assets/549428/24476699/b6d35a5a-14aa-11e7-884c-6b2f73155160.png)

![image](https://cloud.githubusercontent.com/assets/549428/24476728/d112a4de-14aa-11e7-821b-90157829f439.png)

**Comment by intrepidocabral** [comment]
A parte de ter o thumbnail funcionou. Precisa do icon. 

- 2a parte dessa issue: 
![ex2](https://cloud.githubusercontent.com/assets/641411/24679569/f4a02616-1963-11e7-973f-516c60759df9.png)

- Veja como pode ficar: 
![curso- tim faz ciencia](https://cloud.githubusercontent.com/assets/641411/24679981/8e4ed19e-1965-11e7-8a0e-44ac32e52c56.png)

Dá pra colocar o font-awesome ou esse ícone:
![icon_text](https://cloud.githubusercontent.com/assets/641411/24680049/c7fa7f6a-1965-11e7-9b58-25780af5a48f.png)

**Comment by moacirmoda** [comment]
Feito, com ícone do font-awesome. (caso não apareça nos ambientes de teste, aperte Ctrl + F5)

**Comment by intrepidocabral** [comment]
ótimo!

**Comment by Nathlis** [comment]
Está funcionando tudo certinho, porém somente no modo editável (em ambos os temas), ou seja, somente o professor visualiza essa funcionalidade: 

![tim tec_1](https://cloud.githubusercontent.com/assets/18741130/25176672/5ed45ca6-24d5-11e7-8753-a5f27e78d587.png)


Visualização de um aluno fazendo o curso:
![tim tec_2](https://cloud.githubusercontent.com/assets/18741130/25176688/6de5cc70-24d5-11e7-8c9a-3b95b3197b46.png)

**Comment by intrepidocabral** [comment]
> Está funcionando tudo certinho, porém somente no modo editável (em ambos os temas), ou seja, somente o professor visualiza essa funcionalidade:

@Nathlis nesse caso sempre foi assim, então não é bug é melhoria. Sugiro abrir uma issue nova, ok? Estou fechado por conta dessa situação em específico. Por favor, abra uma nova issue e coloque como enhacement.
