### ISSUE TITLE
bug: engine de mensagens super lenta

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#103]
testamos o envio de mensagem para 1 usuário e demorou 20 minutos para sair da tela de loading:

![image](https://cloud.githubusercontent.com/assets/641411/24374426/34a67346-130b-11e7-936b-8eddfa69417a.png)

**Comment by moacirmoda** [comment]
Encontrei um pequeno bug que não trazia o email na busca de usuários para envios únicos. Foi corrigido.

Fiz o teste tentando enviar email para uma turma pequena (2 alunos) e para um usuário único e tudo correu bem rápido. Se tentarmos enviar para a turma toda vai demorar, porque estamos falando de turmas de mais de mil alunos. Desde a implementação primária já demorava. Para que possamos conseguir enviar em quantidades massivas, é preciso partir para uma solução alternativa, como um serviço de disparo de emails.

**Comment by intrepidocabral** [comment]
ok! Testado e aprovado.
