### ISSUE TITLE
Bug: Importação e exportação de cursos não funciona

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#105]
A importação de cursos não está funcionando em nenhum ambiente com nova versão. 

Veja comportamento com bug na IMPORTAÇÃO: https://youtu.be/dJ5hjVVo9BI
Veja comportamento com bug na EXPORTAÇÃO: https://youtu.be/GaMAR-4AMRQ

Vale lembrar que os cursos vem daqui: https://github.com/institutotim/timtec-cursos

**Comment by moacirmoda** [comment]
Gastei uma manhã inteira tentando entender e corrigir este erro. Trata-se consequências da atualização do django-rest. Depois de tentar diversas alternativas e não chegar a uma solução concreta, eu decidi não prosseguir antes de conversar sobre o problema. O que acham?

O mesmo vale para o #101.

**Comment by moacirmoda** [comment]
Aparentemente resolvido. Favor testar.

**Comment by intrepidocabral** [comment]
Fiz um deploy do zero nesse ambiente: http://if.dev.timtec.com.br
Também deletei os cursos desse ambiente e fiz teste aqui: http://li1109-208.members.linode.com

Resultado: alguns cursos funcionam, outros não. 

**Lsta dos cursos que funcionam com importação via painel**
- [x] Autodefesa digital
- [x] Boas práticas no desenvolvimento de software
- [x] Empreendedorismo 2
- [x] Empreendedorismo 3
- [x] API Rest
- [x] Desenvolvimento em Python
- [x] Introdução SQL
- [x] Introdução a criação de sites
- [x] Mooc e novas formas de aprendizagem

Lista de cursos que NÃO funcionam com importação: 
- [x] Android
- [x] Backend
- [x] Css3
- [x] Desenho de jogos
- [x] Desenvolvimento Front-end
- [x] Desenvolvimento web com Angular
- [x] Desenvolvimento web com php
- [x] HTML5
- [x] Introdução ao php
- [x] Javascript conceitos e bibliotecas
- [x] Lógica de programação
- [x] Desenvolvimento de jogos
- [x] Produção de textos
- [x] Programação java
- [x] Publicação digital
- [x] Tim faz ciencia
- [x] Ux e ui
- [x] videos educacionais para web

**Comment by robertkapa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Novo deploy TIM Tec - V 4.0](https://trello.com/c/2VCTgimB/45-novo-deploy-tim-tec-v-4-0)

**Comment by moacirmoda** [comment]
Qual foi o comportamento dos que não funcionaram?
Há mensagens de erro? Simplesmente não foi?
Você me passando essas informações fica mais fácil de conseguir identificar
e corrigir o erro.

**Comment by intrepidocabral** [comment]
O processo de importação se dá da seguinte forma: 
1 - Usuário admin loga na plataforma
2 - Usuário admin navega pelo menu **administração** > **cursos** > **importar curso** (http://if.dev.timtec.com.br/admin/courses/)
3 - Os pacotes de cursospara upload são esses: https://github.com/institutotim/timtec-cursos

Acho que vc pode pegar os pacotes dos cursos que mencionei que não funcionaram e fazer o upload no seu ambiente local, observando os logs da ferramenta. Isso vai dar pistas do que está acontecendo. Os comportamentos são diversos: tem cursos que não faz upload, tem curso que mostra uma mensagem generica (alert) dizendo que não foi possível importar o curso, enfim, tem mais de um erro envolvido. 

Aqui está o vídeo documentando como foi feito o teste, tem todo comportamento. É possível ver que o console do browser estava ativado (f12) para ver se aparecia alguma coisa. Teste foi feito no ambiente com deploy do zero (http://if.dev.timtec.com.br) e no navegador firefox: https://youtu.be/0BEsDoPHGfY

@Nathlis pode testar no chrome?

**Comment by moacirmoda** [comment]
Corrigido e todos testados localmente. Favor testar nos novos ambientes.

**Comment by intrepidocabral** [comment]
Testei nos dois ambientes: no ambiente de update de versão v3.3 para 4.1 com tema timtec (http://li1109-208.members.linode.com) e no ambiente instalação zerada com tema if (http://if.dev.timtec.com.br). 

Todos os cursos subiram, com exceção dos cursos de desenvolvimento de jogos e produção de texto no ambiente de update (http://li1109-208.members.linode.com). Os cursos são esses:
https://github.com/institutotim/timtec-cursos/blob/master/producaodetextos.tar.gz
https://github.com/institutotim/timtec-cursos/blob/master/dev-jogos.tar.gz

Essa foi a saída: 
![selecao_001](https://cloud.githubusercontent.com/assets/641411/24929388/21cf2f6a-1edc-11e7-87c9-120c6cb85732.png)

Acredito que esse err pode estar relacionado ao limite de upload de arquivos da plataforma.
