### ISSUE TITLE
BUG: numeração de unidades (capítulos) erradas

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#106]
Quando eu deleto uma aula dentro de uma unidade e crio outra, o sistema não está númerando corretamente. Ele está pulando números. A @Nathlis pode dar um print sobre isso.

**Comment by Nathlis** [comment]
Testado no curso de Apache Wicket (não consigo testar em um curso novo porque está com problemas na hora de salvar). Segue print do que acontece:

![tim tec_numeracao capitulos](https://cloud.githubusercontent.com/assets/18741130/24401358/73a0b05a-138a-11e7-85fb-3e80daf9ee98.png)

**Comment by moacirmoda** [comment]
Não consegui simular o problema. Testei neste mesmo curso e mesma aula, na instância da Linode.
Se puderem verificar novamente e, caso continue, gravar um vídeo, seria melhor.

**Comment by Nathlis** [comment]
Oi @moacirmoda você testou no modo editável ou normal? Fiz outro teste, segue prints (não sei fazer vídeo que o Cabral faz)

No modo editável fica tudo certinho:
![aula aula 1 introducao instalacao e hello word](https://cloud.githubusercontent.com/assets/18741130/24501733/3036fdd6-1521-11e7-898d-074d1dee27fa.png)

Depois que salva você vai visualizar como aluno e acaba ficando assim:
![tim tec](https://cloud.githubusercontent.com/assets/18741130/24501754/410a8646-1521-11e7-8797-9e70784fd098.png)

**Comment by moacirmoda** [comment]
Resolvido.

**Comment by intrepidocabral** [comment]
ótimo! resolvido.
