### ISSUE TITLE
Bug: materiais adicionais não funciona

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#107]
Cada curso tem uma sessão de upload de arquivos (Materiais Adicionais). Essa sessão não está funcionando. 

Como deveria funcionar (Deveria fazer o upload normalmente e organizar dessa forma que está a direita): 
![selecao_035](https://cloud.githubusercontent.com/assets/641411/24669295/40bdb4ec-1940-11e7-8409-f098d2eb6a31.png)

Como está (não faz o upload e não gera lista de arquivos): 

![selecao_033](https://cloud.githubusercontent.com/assets/641411/24669244/1c079a0a-1940-11e7-8e9e-12ff1c63adc2.png)

![selecao_034](https://cloud.githubusercontent.com/assets/641411/24669245/201b70ee-1940-11e7-8e7e-f9733f206f63.png)

**Comment by intrepidocabral** [comment]
ainda pendente...

**Comment by moacirmoda** [comment]
Corrigido.

**Comment by intrepidocabral** [comment]
Ainda temos dois problemas

**PROBLEMA 1**

- [x] os arquivos não estão sendo apagados. Botão de delete não funciona. 

![selecao_002](https://cloud.githubusercontent.com/assets/641411/24930915/a071b54a-1ee1-11e7-898f-7ae6fa12bdf6.png)

**PROBLEMA 2**

- [x] Os links gerados abrem na mesma página, causando um certo desconforto/confusão. Colocar target="_blank" na engine dos links. 

![selecao_018](https://cloud.githubusercontent.com/assets/641411/25146398/1a13ea0e-244a-11e7-9bce-d62e5fe02a96.png)

**Comment by moacirmoda** [comment]
Ambos corrigidos.

**Comment by intrepidocabral** [comment]
ok!
