### ISSUE TITLE
Bug: mensagem de finalização dos cursos

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#111]
ao concluir um determinado curso, a mensagem final aparece com bug. Isso acontece nos dois temas. 

A mensagem é mostrada ao aluno que chega no final do curso, isto é, que realiza a última aula independente das aulas intermediárias entre o começo e o fim. No entanto, a mensagem não é clara quando ao percentual realizado e o necessário e também, neste caso, fizemos o teste com um usuário que havia SIM realizado todo conjunto de aulas do curso. Portanto a mensagem de percentual pendente não deveria aparecer. 

- [x] Bug 1: usuário realizou todo conjunto de aulas e mesmo assim o aplicação mostrou uma mensagem de pendencia;

![exercicios_comprovante_android](https://cloud.githubusercontent.com/assets/641411/25103075/783d9f08-2391-11e7-9ce4-bec4703fa3aa.png)

![exercicios_comprovante_java](https://cloud.githubusercontent.com/assets/641411/25103081/7c08afe2-2391-11e7-80a9-c9d4d6edf8fb.png)

**Comment by Nathlis** [comment]
Isso também acontece com um curso que não possui atividades, exemplo no curso Introdução a Criação de Sites:

![introducao a criacao de sites](https://cloud.githubusercontent.com/assets/18741130/25177913/10a8d9a8-24da-11e7-8235-2291beabaa7e.png)
