### ISSUE TITLE
Bug: no form de criação do curso, campo de data aparece no formato americano e sem máscara

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#112]
O problema acontece nos 2 temas, isto é, tanto no tema dos IFs quanto no tema timtec. No entanto, no tema timtec a engine chega a salvar o curso, no tema dos ifs nem salvar salva. Ver última imagem. 

Inicialmente aparece assim: 
![selecao_003](https://cloud.githubusercontent.com/assets/641411/25136021/40ad4c5c-242a-11e7-9a5f-ed79d1b1ae43.png)

Depois, quando fazemos uma tentativa de preenchimento, aparece assim e mesmo assim não salva: 
![selecao_005](https://cloud.githubusercontent.com/assets/641411/25136109/701a0bba-242a-11e7-8c31-f046fdfcfeda.png)

**Comment by moacirmoda** [comment]
Corrigido.
