### ISSUE TITLE
Bug: video introdutório não salva

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#114]
Tentamos nos 2 temas, na criação de curso novo, video introdutório não salva nem por reza! 

![selecao_007](https://cloud.githubusercontent.com/assets/641411/25137645/c07c3070-242e-11e7-85cd-c3a1cee7c6d2.png)

![selecao_006](https://cloud.githubusercontent.com/assets/641411/25137653/c4938b2c-242e-11e7-9da0-72aab476894b.png)

**Comment by moacirmoda** [comment]
Já chegaram a checar se a chave do youtube foi setada corretamente? Muitas
vezes o problema está na chave.

**Comment by Nathlis** [comment]
Oi @moacirmoda testamos aqui e não é chave..

**Comment by moacirmoda** [comment]
Corrigido.
