### ISSUE TITLE
bug: informações de professor não são salvas

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#115]
O sistema possui 2 modos de dados para vincular professores a um determinado curso. O primeiro modo é vinculando um usuário já existente (o sistema faz essa pergunta quando o admin vai cadastrar/vincular um professor a um curso) e cadastrado na plataforma ao curso em questão. O segundo modo é preenchendo um pequeno form auxiliar (modal) com 3 campos: nome, biografia e fotografia (upload). 

Ocorre que o segundo modo não está mais funcionando. 

Ver vídeo com comportamento bugado: https://youtu.be/etOOLkn8j7U

**Comment by Nathlis** [comment]
No tema TIM Tec, não carrega a foto mas as demais informações salvam:
![6](https://user-images.githubusercontent.com/18741130/28273799-a2f8bc50-6ae5-11e7-86ff-e9c84b99c9a2.png)


No tema do IF ainda persiste o erro:
![7](https://user-images.githubusercontent.com/18741130/28274201-a59a8bd6-6ae6-11e7-9b28-a4fdd5238dcb.png)
