### ISSUE TITLE
Bug: no tema timtec, home thumbnails dos cursos está com css/js estourando

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#116]
Comportamento esperado: 
![selecao_008](https://cloud.githubusercontent.com/assets/641411/25138365/b7fa6a32-2430-11e7-92c4-bcf6084af6ae.png)

Apesar do botão estar centralizado, a imagem não estoura: 
![selecao_009](https://cloud.githubusercontent.com/assets/641411/25138375/bed2938e-2430-11e7-8567-463d2ce76f61.png)

No tema timtec só funciona corretamente em thumbnail e não em HOME THUMBNAIL. Veja aqui correto: 
![selecao_010](https://cloud.githubusercontent.com/assets/641411/25138445/ea82a140-2430-11e7-8cdf-23b54eb4bdff.png)

Comportamento com bug: 
![selecao_011](https://cloud.githubusercontent.com/assets/641411/25138399/cff78016-2430-11e7-88a1-33623f0eb20b.png)

**Comment by moacirmoda** [comment]
Corrigido.

**Comment by intrepidocabral** [comment]
ok!
