### ISSUE TITLE
label: trocar "unidades" por "capítulos"

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#117]
![selecao_013](https://cloud.githubusercontent.com/assets/641411/25139313/4321b730-2433-11e7-99b0-30fa3d25716e.png)

**Comment by GustavoVS** [comment]
@Nathlis @photonauta35 deem uma revisada em todos os lugares que com essa nomenclatura, por favor

**Comment by GustavoVS** [comment]
Algumas traduções ficaram incorretas no tema. Movendo para In Progress.

**Comment by intrepidocabral** [comment]
Vi isso hj: 

![selecao_037](https://cloud.githubusercontent.com/assets/641411/25454703/c44a8794-2aa3-11e7-9103-255f5607f0cd.png)
