### ISSUE TITLE
Bug: no tema dos ifs, criação de novas unidades não persiste

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#118]
Ao tentar criar uma nova aula, na inserção de um novo capítulo (unidade), a aplicação não salva o conteúdo. Isso acontece no caso da inserção de vídeos. 

Ver issue #77 

![selecao_014](https://cloud.githubusercontent.com/assets/641411/25139513/db3bd438-2433-11e7-9ff8-ff07ae824e63.png)

**Comment by moacirmoda** [comment]
Não se trata de bug, mas sim má configuração. 
Adicionei a chave da Api do Youtube e voltou a funcionar.

**Comment by intrepidocabral** [comment]
ok!
