### ISSUE TITLE
Interação "next" e "previous" na navegação de conteúdos entre capitulos/aulas

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#119]
Quando um determinado aluno navega em um curso, o sistema identifica o progresso através da finalização dos vídeos. Uma vez que o vídeo é assistido, isto é, quando o vídeo chega ao final, o sistema computa o capítulo/aula como "realizado". Essa interação é importante tanto para marcar o progresso do estudante como para automaticamente levar o aluno ao próximo passo. 

Atualmente, quando o aluno passa por uma aula cujo conteúdo não seja de vídeo, isto é, conteúdo de texto/imagem, essa marcação como "aula vista" não é computada e não há botão de next ou previous para avançar ou retroceder nas aulas. 

![selecao_017](https://cloud.githubusercontent.com/assets/641411/25145251/035ebe36-2447-11e7-9959-080c3a0d407b.png)

**Comment by GustavoVS** [comment]
Quando o capítulo tiver atividade de leitura, precisa da funcionalidade ir/voltar.

Quando é apenas uma página estática só precisa da funcionalidade **avançar** e ao clicar em **avançar**, marcar o capítulo como feito.
