### ISSUE TITLE
Portar temas "Instituto TIM" e "IF-colors" para app, com vistas às melhorias da nova versão 4.0

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#12]

**Comment by moacirmoda** [comment]
- [x] tema ifs-colors
- [x] tema timtec

**Comment by moacirmoda** [comment]
No tema if_theme (antigo ifs-colors) temos um problema: A imagem de fundo da home antigamente era sobrescrita Porém, neste arranjo de apps externas, a imagem selecionada é a do tema default, [segundo esta explicação](http://stackoverflow.com/a/11420157). Como procedemos? Criamos um arquivo less no tema que sobrescreve a imagem, e renomeamos a imagem para ela ser coletada?

**Comment by moacirmoda** [comment]
- Tema ifs-colors alterado para if_theme. (https://github.com/institutotim/timtec-theme-if)
- Tema timtec alterado para timtec_theme (https://github.com/institutotim/timtec-theme-timtec)

Foi necesário alterar o nome dos temas pois o tema de nome timtec estava entrando em conflito no pip com a app timtec, dentro do próprio software.

**Comment by moacirmoda** [comment]
@robertkapa precisamos testar. Vamos colocar em prática já aquela disposição de ambientes citada no #47.

**Comment by intrepidocabral** [comment]
Excelente. Os temas estão separados agora e estão estendendo o tema base, certo @moacirmoda ? acho que se for essa linha, precisamos sim de uma alternativa para reprocessar no tema extendido as coisas como a imagem destacada. Nesse caso sim, vale ter um less/sass do tema.
