### ISSUE TITLE
Layout da página home dos cursos - Modo aluno

### ISSUE THREAD

**Issue by Nathlis** [institutotim/timtec#120]
Está funcionando tudo certinho, porém somente no modo editável (em ambos os temas), ou seja, somente o professor visualiza essa funcionalidade:

![tim tec_1](https://cloud.githubusercontent.com/assets/18741130/25191310/8fb3f66c-2505-11e7-883a-1fc6a0fc7f25.png)

Visualização de um aluno fazendo o curso:
![tim tec_2](https://cloud.githubusercontent.com/assets/18741130/25191318/979b9498-2505-11e7-84f8-edd8f52f8003.png)

**Comment by intrepidocabral** [comment]
Acabei de verificar e o erro ainda persiste. Vou arrumar isso.
