### ISSUE TITLE
bug: atividade não mostra retorno

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#121]
São dois erros. Um de falta de retorno (feedback) para o usuário quando a opção da atividade está incorreta e o outro é relacionado a um setting após a interação(clique no botão enviar) quando o usuário escolhe a opção errada. 

Roteiro de como identificar o erro: 
1 - Logue no ambiente (http://li724-11.members.linode.com ou http://if.dev.timtec.com.br) com qualquer usuário (aluno, professor ou admin);
2 - Acesse um curso que contém atividade, como por exemplo do tipo multipla escolha. Exemplo (ver atividades 1 ou 2): http://li724-11.members.linode.com/course/css3/lesson/aula-1-teste-de-atividades#/1

![selecao_045](https://cloud.githubusercontent.com/assets/641411/25636710/9d30ee46-2f58-11e7-96e5-2a0144b18872.png)

![selecao_046](https://cloud.githubusercontent.com/assets/641411/25636713/a0ae089c-2f58-11e7-9703-09c34e9a6ea8.png)

**Comment by GustavoVS** [comment]
Resolvido
