### ISSUE TITLE
Atividade de leitura com view mostrando metadados

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#130]
Ao editar uma atividade de leitura, os metadados de edição são mostrados ao usuário. 

![selecao_044](https://cloud.githubusercontent.com/assets/641411/25636929/617c13de-2f59-11e7-87d5-3e6c903c5b5e.png)

**Comment by GustavoVS** [comment]
Falta o botão (issue https://github.com/institutotim/timtec/issues/119)
