### ISSUE TITLE
Bug: tela de gerenciamento de turmas está bugada

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#133]
Não sai dessa tela, independente do curso ou número de inscritos. Esse problema impede de criar certificados. 

![selecao_006](https://cloud.githubusercontent.com/assets/641411/25724805/9cb68dbc-30f3-11e7-9bdb-7253d89a973d.png)

**Comment by Nathlis** [comment]
Em ambos os temas, na turma padrão os alunos não carregam, além de que o título não deveria manter o nome do curso, já que se trata da turma padrão?

**Tema TIM Tec:**
![2](https://user-images.githubusercontent.com/18741130/28268762-d9ae7e70-6ad5-11e7-9c05-9fca5dcb76e8.png)

**Tema IF:**
![1](https://user-images.githubusercontent.com/18741130/28268757-d56ae6d2-6ad5-11e7-80dd-09bf405b083c.png)


OBS: Esse erro não ocorre em turmas que foram criadas, os alunos são carregados normalmente.
