### ISSUE TITLE
Bug: página sobre bugada

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#134]
![selecao_031](https://user-images.githubusercontent.com/641411/27353515-9fbfedb2-55da-11e7-9e41-d628c666a1f1.png)

Estranhamente a página está bugada, acusando esse erro: https://docs.angularjs.org/error/$controller/ctrlreg?p0=FlatPageCtrl

No entanto as coisas parecem normais: 
![selecao_032](https://user-images.githubusercontent.com/641411/27353534-b6f7ac0e-55da-11e7-890b-31c18c909156.png)

![selecao_033](https://user-images.githubusercontent.com/641411/27353539-bad5d7a6-55da-11e7-8ee3-e4b9a8a33889.png)

Outra coisa estranha é que quando clico na página sem ser admin, com debug ligado, sou levado a uma página de erro que diz que não há uma view:

![selecao_034](https://user-images.githubusercontent.com/641411/27353677-4d87246a-55db-11e7-8ef4-9069a70257c5.png)

**Comment by Nathlis** [comment]
**Tema TIM Tec e no tema IF:**

Quando **não está logado** na plataforma, aparece erro:
![4](https://user-images.githubusercontent.com/18741130/28271071-fb70fbca-6add-11e7-8d15-eb3888e12f72.png)

Logado no modo estudante:
![5](https://user-images.githubusercontent.com/18741130/28271379-b94f150a-6ade-11e7-90d9-c7b10d485b55.png)


No modo ADM funciona.
