### ISSUE TITLE
Bug: página da "mensagem" individual está quebrada. Não abre. 

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#135]
![selecao_003](https://cloud.githubusercontent.com/assets/641411/25823588/ef7536d0-3412-11e7-9cfb-9a3224d5de9e.png)

**Comment by Nathlis** [comment]
O problema da mensagem quebrada foi arrumado:

![homol mooc tim tec](https://user-images.githubusercontent.com/18741130/27929784-b1e4facc-626a-11e7-87ee-ae8f495e3ccf.png)

Porém tem duas questões nessa mensagem:

1 - O link que aparece não possui hyperlink
2 - Após copiar e colar o endereço aparece a seguinte página:

![example domain](https://user-images.githubusercontent.com/18741130/27929822-df219612-626a-11e7-8ff3-e638d13cdc78.png)

**OBS: essa mensagem veio da opção "SEGUIR" no fórum. Quando a pessoa resolve seguir uma publicação do fórum ela não recebe e-mail, ela acaba recebendo uma mensagem em seu perfil.**
