### ISSUE TITLE
implementar favicon nos temas

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#14]
Implementar favicon e documentar como fazer isso nos dois temas (instituto tim e if). Usar estes favicons abaixo. 

Referência:
- https://github.com/audreyr/favicon-cheat-sheet

[timtec_favicons.zip](https://github.com/institutotim/timtec/files/437696/timtec_favicons.zip)

**Comment by moacirmoda** [comment]
Coloquei o icon default. Não consegui avançar nas peculiaridades do favicon-cheat-sheet pois preciso dos icones nos seguintes formatos:
- 152x152 em png
- 144x144 em png
- 70x70 em png
- 150x150 em png
- 310x150 em png
- 310x310 em png
- 196x196 em png

**Comment by intrepidocabral** [comment]
ok! Segue imagens solicitadas. 
[timtec_icons.zip](https://github.com/institutotim/timtec/files/522475/timtec_icons.zip)
