### ISSUE TITLE
URL aula não privada

### ISSUE THREAD

**Issue by GustavoVS** [institutotim/timtec#160]
Aulas que não estão públicas podem ser acessadas via URL.
Seja pelo curso não ter sido lançado ou pelo aula estar como rascunho

![image](https://user-images.githubusercontent.com/7750643/27805868-8a12e568-600d-11e7-99c0-0b0df7e9ad75.png)

![image](https://user-images.githubusercontent.com/7750643/27805908-c516e10a-600d-11e7-9989-eafb708f9837.png)

**Comment by Nathlis** [comment]
Temos a seguinte situação: Um curso é lançado e todas as suas aulas estão públicas. Existem alunos fazendo esse curso. Porém em determinado momento o ADM colocou as aulas como rascunho. O aluno tenta acessar o curso e encontra:

![3](https://user-images.githubusercontent.com/18741130/28270568-54161f00-6adc-11e7-9906-38d240641da0.png)

Isso acontece porque o aluno já estava fazendo o curso e ao procurar a página da aula (onde ele parou) não é possível encontrar. 

O certo seria o redirecionamento para a página introdutória, como acontece antes das aulas se tornarem públicas.
