### ISSUE TITLE
bug: anotações mostra tag template do django em ambos os temas

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#162]
![selecao_049](https://user-images.githubusercontent.com/641411/27840212-929a6f92-60cd-11e7-8e0b-37c2d3348d58.png)

![selecao_050](https://user-images.githubusercontent.com/641411/27840209-8c7168b4-60cd-11e7-80ce-06d43472d068.png)

**Comment by Nathlis** [comment]
No tema IF ainda está quebrado:

![9](https://user-images.githubusercontent.com/18741130/28280047-d858d106-6af8-11e7-8e8e-0708e2b2594d.png)

No tema TIM Tec ok.
