### ISSUE TITLE
Duplicação de mensagens no fórum

### ISSUE THREAD

**Issue by Nathlis** [institutotim/timtec#167]
Quando é feita uma pergunta no fórum e outras pessoas comentam nessa pergunta, a cada resposta é duplicada a mensagem na página inicial do fórum do curso.

![photo4931479121851164636](https://user-images.githubusercontent.com/18741130/29228364-d3034d10-7eaf-11e7-9c13-369e7acf6d5a.jpg)

**Comment by Nathlis** [comment]
Quando você escreve uma pergunta no fórum e ao clicar em "ENVIAR" não aparece na lista abaixo.. somente aparece após atualizar a página.

**Comment by intrepidocabral** [comment]
@Nathlis essa já tá resolvida ne? podemos fechar?

**Comment by Nathlis** [comment]
Resolvido.
