### ISSUE TITLE
Botão de excluir e scroll caixa de mensagens

### ISSUE THREAD

**Issue by Nathlis** [institutotim/timtec#168]
Implementar um botão de excluir na caixa de mensagem e um scroll para quando tiver mais de 6 mensagens.

![photo4931479121851164637](https://user-images.githubusercontent.com/18741130/29228530-748b33aa-7eb0-11e7-92bf-79dca573cef9.jpg)

**Comment by LaFabbrica** [comment]
@Nathlis não era melhor fazermos uma página para gerenciamento dessas mensagens?
