### ISSUE TITLE
Melhorias na engine de mensagens do curso

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#17]
No painel de um curso há a opção de enviar mensagens para os alunos de uma determinada turma ou de todas. Ex. de página de mensagens de um determinado curso: 
- http://demo.timtec.com.br/admin/course/10/messages
- http://mooc.timtec.com.br/course/html5/messages/

**Implementar melhorias em todos os temas (default, timtec e if):** 
- [x] Implementar editor wyswyg na edição de mensagens do professor/coordenador/admin para os alunos. As opções disponíveis podem ser simples, tais como: 
- negrito
- itálico
- lista
- link

Usar tyni mce: ui-tinymce (https://github.com/angular-ui/ui-tinymce)
- [x] Armazenar as mensagens enviadas pelos professores/coordenadores/admins de maneira que seja possível ver o histórico de mensagens enviadas pela plataforma. O histórico deve ser evidentemente somente leitura e deve mostrar: 
- para quais turmas a mensagem foi enviada
- quando a mensagem foi enviada
- qual conteúdo da mensagem
- quem enviou a mensagem

![selecao_011](https://cloud.githubusercontent.com/assets/641411/17981383/e5678da8-6ad9-11e6-8cac-c20f7a8579c7.png)

![selecao_012](https://cloud.githubusercontent.com/assets/641411/17981462/3b2dbeb0-6ada-11e6-9dd7-20e299fd16b3.png)

**Comment by brunosmartin** [comment]
Pessoal, na versão 4.0-dev estamos usando o ui-tinymce (https://github.com/angular-ui/ui-tinymce)
Vamos usar este também? Pq vai se difícil fazer esta tarefa usando editro markdown, pois será preciso renderizar a mensagem antes de enviar por email.

**Comment by intrepidocabral** [comment]
ok, @brunosmartin! Sugestão acepted.

**Comment by intrepidocabral** [comment]
Testei e está bugado no staging.

![selecao_035](https://cloud.githubusercontent.com/assets/641411/18446627/8eaa8316-78f9-11e6-9f1a-1b4780fbcec9.png)

**Comment by moacirmoda** [comment]
Problema resolvido. Alguns arquivos não estavam sendo importados e comprimidos na homologação. Problema não foi identificado no dev pois não há compressão neste ambiente.

![captura de tela de 2016-09-15 12 12 37](https://cloud.githubusercontent.com/assets/549428/18555310/d3699f64-7b3d-11e6-966e-9fe3eb89d66b.png)

**Comment by Bruplf** [comment]
Não conseguimos testar a opção "links" conforme descrito inicialmente.

**Comment by moacirmoda** [comment]
@Bruplf a função não havia sido ativada. Testar novamente, por favor. 

Obs: Caso não apareça, atualizar a página utilizando Ctrl + F5.

**Comment by Bruplf** [comment]
@moacirmoda  testei e as duas funcionalidades estão funcionando. Porém, achei o histórico das mensagens meio ruim de ver. Quando clica no "listar mais" fica uma lista gigante que não diminui. Deveria aparecer o número da turma apenas e a mensagem. Caso o professor queira ver a turma interna ele clica na mensagem e ela abre uma caixa. É possível?

**Comment by moacirmoda** [comment]
@Bruplf coloquei um botão que mostra/esconde a lista de destinatários do email.

**Comment by intrepidocabral** [comment]
Testamos aqui e verificamos que a página esta pública. 
- [x] Ela deveria ser acessível apenas aos usuários logados com poder de edição do curso.

Outro dado importante do teste: a tela ficou intermitente.
- [x] As mensagens apareceram e depois não apareceram mais. Conforme davamos f5, oscilava entre aparecer ou não. 

![selecao_008](https://cloud.githubusercontent.com/assets/641411/18879213/d3abb6fe-84a9-11e6-8aca-97b3aaf5d77f.png)

**Comment by moacirmoda** [comment]
Fiz algumas melhorias visuais no envio da mensagem e na listagem das mensagens, que escode a intermitência (que é causada por lentidão na API, estou verificando).

**Comment by moacirmoda** [comment]
- [x] informar que a informação está sendo carregada
- [x] otimizar o carregamento das informações (está muito lento)
- [x] o email do aluno não está aparecendo na listagem dos destinatários
- [x] permitir que o aluno visualize somente as mensagens que foram enviadas para ele (na listagem, filtrar e quando tentar acessar uma nao permitida, bloquear)
- [x] não exibir lista de emails para alunos

**Comment by intrepidocabral** [comment]
Acho que ficou muito bom. Testei aqui e deu certo. Só precisa traduzir o botão "details" para "ver mais" ou "Detalhes". 

![download 1](https://cloud.githubusercontent.com/assets/641411/19002689/963227a0-8723-11e6-9f97-65287a5b0aa3.png)

**Comment by moacirmoda** [comment]
Já atualizei... havia sido traduzido, porém não sei o motivo que não estava em produção.
