### ISSUE TITLE
Criar e implementar uma página "forbidden" customizada

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#18]
Quando um usuário comum/anonimo tenta acessar uma página privada ele recebe um erro 403 (forbidden) ou quando não está logado recebe um erro 500. O usuário deveria receber uma página tratada, dizendo (em português): 

> Um erro aconteceu ou você não tem permissão para acessar essa página. Volte para a home ou contacte o administrador: admin@url.com.br

O layout da página pode ser default do tema. Não deve ser essa página do django:

![selecao_014](https://cloud.githubusercontent.com/assets/641411/17982279/8af2a002-6add-11e6-90ae-cdd0a000832e.png)

**Comment by Bruplf** [comment]
Fizemos o teste e acessamos uma página http://timtec.conexaobrasil.org/admin/courses/ como usuário anônimo. Aparece uma mensagem de erro diferente da mensagem inicial acima, mas fizemos algumas correções e a nova mensagem deve ser como segue no print.
![erro de pagina](https://cloud.githubusercontent.com/assets/22303766/18645441/914eba26-7e83-11e6-8ed4-065a8c60408a.png)

**Comment by Bruplf** [comment]
Verificamos também que o botão "entrar" do menu, nesta página, não está acessível.

**Comment by moacirmoda** [comment]
Melhorei o layout, traduzi os textos e consertei o botão entrar. Favor testar.
