### ISSUE TITLE
Adicionar "notifications"

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#19]
No menu, quando usuário estiver logado, mostrar um item de "notificações" que mostra mensagens enviadas pelos professores. As mensagens enviadas pela plataforma devem ficar armazenadas na base e serem visualizadas conforme issue #17 

No caso deste menu, deve aparecer um item "notificações" no qual o usuário possa ver as mensagens enviadas para a turma dele. O menu deve redirecionar para uma página com notifications. 

ex.:
![selecao_017](https://cloud.githubusercontent.com/assets/641411/18014615/1ba3ac4c-6b9a-11e6-836f-60ab3e15ac31.png)

**Comment by moacirmoda** [comment]
@robertkapa vamos executar esta funcionalidade agora, ou esperar para desenvolver na versão 4.0?

**Comment by moacirmoda** [comment]
- trabalhar em cima dos messages dos professores

**Comment by moacirmoda** [comment]
Lembrar do header modularizado do branch paralapraca.

**Comment by moacirmoda** [comment]
Feito no tema IF, falta aplicar estilo no tema timtec.
