### ISSUE TITLE
Bug: em atividades, no modo "true or false" usuário deve ser avisado quando não marcou alguma alternativa

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#20]
Hoje a atividade "true or false" só avisa ao usuário se houve erro ou acerto do exercício como um todo, mas quando o usuário não respondeu todas as perguntas ela sempre diz que esta errado. Neste caso, o sistema deveria checar antes (validação) se todas as opções foram marcadas. Quando o usuário tentar submeter a resposta, se tiver alguma opção em branco, o feedback deveria dizer "preencha todas as alternativas de verdadeiro ou falso antes de proceguir". 

Ex.:
Logado como admin (essa é a montagem da atividade): 
http://demo.timtec.com.br/admin/courses/1/lessons/1/

![selecao_018](https://cloud.githubusercontent.com/assets/641411/18014949/bddd1ec0-6b9b-11e6-96c7-bbaeffb01229.png)

Logado como aluno (quando o aluno realiza a atividade). Repare abaixo que o aluno marcou apenas um opção e por isso o feedback foi "sua resposta está incorreta". A mensagem deveria dizer "preencha todas as alternativas antes de prosseguir". Depois de preencher todas, daí sim o sistema deveria checar quais estão corretas e quais estão erradas e mostrar ao usuário a mensagem "sua resposta está incorreta". 
![selecao_020](https://cloud.githubusercontent.com/assets/641411/18014972/d708b1fc-6b9b-11e6-9293-b1fb705de1b9.png)

> ## Correção a ser implementada em todos os temas: default, timtec e if

**Comment by Bruplf** [comment]
Quando abre o teste todos os itens estão ticados. É isso mesmo? Se for isso está ok.

**Comment by moacirmoda** [comment]
@Bruplf não, o comportamento, pelo o que entendi, deve ser igual ao das screenshots abaixo:

![captura de tela de 2016-09-21 15 00 13](https://cloud.githubusercontent.com/assets/549428/18722758/55974e46-800c-11e6-856b-100d1541ec8d.png)
![captura de tela de 2016-09-21 14 58 34](https://cloud.githubusercontent.com/assets/549428/18722763/5afbce16-800c-11e6-8d40-e140ba0b8482.png)
![captura de tela de 2016-09-21 14 58 44](https://cloud.githubusercontent.com/assets/549428/18722764/5b1d7750-800c-11e6-959f-9efdeb0e0129.png)
![captura de tela de 2016-09-21 14 58 55](https://cloud.githubusercontent.com/assets/549428/18722765/5b2556dc-800c-11e6-864b-493edd78c26d.png)
![captura de tela de 2016-09-21 14 59 03](https://cloud.githubusercontent.com/assets/549428/18722766/5b2616c6-800c-11e6-8c50-175680f54c8a.png)

**Comment by GustavoVS** [comment]
- [ ] Remover o feedback positivo
- [ ] Fazer funcionar o negativo
