### ISSUE TITLE
Bug: usuário já registrado ainda consegue ver página de aceitação de termos de uso...

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#21]
http://demo.timtec.com.br/accept_terms/
http://mooc.timtec.com.br/accept_terms/
http://localhost:8080/accept_terms/

Corrigir em todos os temas: default, if e timtec

![bug timtec](https://cloud.githubusercontent.com/assets/69956/11445178/1a3c579c-9511-11e5-837a-4790b9c2c0dd.png)

**Comment by moacirmoda** [comment]
Agora ele redireciona para a home, caso o usuário esteja logado. 

Tentei entender o porque dessa página existir, porém não a vi sendo incluida em nenhum lugar. @bruno_hacklab você sabe para que serve?

**Comment by intrepidocabral** [comment]
Certo! Mas na página de cadastro a opção de termos de uso deve estar ativa. Ver issue #4
