### ISSUE TITLE
Ajuste: dar destaque ao botão "ir para o curso" no tema timtec

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#23]
No tema timtec, na página dos cursos, existe um botão "IR PARA O CURSO".  O botão está pouco visível e se camufla com o fundo. Trocar a cor para verde ou branco, ou alguma cor da paleta da página que de mais destaque. Ver imagem abaixo. 

![selecao_022](https://cloud.githubusercontent.com/assets/641411/18018242/3c962f9e-6bac-11e6-979a-5f8c26430d7a.png)

**Comment by intrepidocabral** [comment]
Não consegui testar. Vamos criar um timtec-tim.conexaobrasil.org no mesmo server de homologação para ter os 2 temas ativos? Assim fica mais fácil das meninas testares aqui as alterações em ambos os temas!

**Comment by moacirmoda** [comment]
Abri o #32 para isso.

**Comment by moacirmoda** [comment]
Testar no endereço: http://23.92.21.39/
