### ISSUE TITLE
Melhorar forma de adicionar usuários as turmas de um curso

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#26]
- [x] implementar busca por nome/email
- [x] implementar checkbox para selecionar os usuários
- [x] implementar um checkbox que selecione todos os usuários resultados da busca

Obs:
Decorrente do #24

**Comment by moacirmoda** [comment]
Implementei de uma forma um pouco diferente, sem os checkboxes. Creio que a usabilidade ficou boa.

**Comment by intrepidocabral** [comment]
Testei a primeira vez e explodiu. Creio que enquanto o sistema está carregando os dados, podia ter um feedback para o usuário aguardar... : 
![selecao_036](https://cloud.githubusercontent.com/assets/641411/18446773/2bb6cbec-78fa-11e6-9450-c93c8dcfaa72.png)

Testei de novo e percebi um erro de layout. Ao selecionar muitos nomes, não está gerando quebra de linha: 
![selecao_037](https://cloud.githubusercontent.com/assets/641411/18446793/4287eb94-78fa-11e6-8076-4160d863ae8e.png)

Por fim, fiz uma busca por email e reparei que na lista não mostra o email. Para melhor usabilidade, deveria ter uma tip dizendo "busque por nome ou email" e mostrar os emails também de cada usuário: 
![selecao_038](https://cloud.githubusercontent.com/assets/641411/18446873/8e48ea6a-78fa-11e6-9247-d3d352dea752.png)

**Comment by moacirmoda** [comment]
Este módulo não havia sido desenvolvido utilizando angular. Portanto, a primeira vista, achei que seria mais proveitoso apenas utilizar um jquery para fazer isso e resolver o problema, deixando a adição do angular para uma segunda oportunidade, no momento de refatoração. Porém, como levantou muitos bugs, resolvi já implementar o Angular. Já está no ambiente de homologação, @robertkapa. Gostaria que validasse, por favor.

**Comment by intrepidocabral** [comment]
Testamos agora e o layout está quebrado. 

![selecao_009](https://cloud.githubusercontent.com/assets/641411/18879451/b5f857d8-84aa-11e6-8ece-035aa975e036.png)

**Comment by moacirmoda** [comment]
Havia um erro de configuração que não minificava corretamente os js, causando o erro somente nos ambientes de staging. Alterei e atualizei os ambientes, e testei. Em ambos funcionou corretamente.
