### ISSUE TITLE
Simplificar o método de emissão de certificados para determinada turma

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#27]
- [x] Remover temporariamente (desabilitar) funcionalidade de avaliação
- [x] Criar formulário que seleciona alunos que terão direito ao certificado.
- Fluxo desejado: 
  - Professor cria turma de certificação*
  - Professor acrescenta alunos em turma de certificação*
  - Professor envia mensagem aos alunos marcando avaliação, alunos realizam avaliação e professor corrige (em fluxo independente ao sistema)*
  - Professor, baseando-se na lista completa de alunos cadastrados naquela turma, seleciona alunos que terão direito ao certificado, clicando no checkbox "liberar certificado".

Obs:
- Relacionado ao #24
- Depende do #26
- * Sistema já contempla essa funcionalidade
- unificar as telas "certificação" e "turmas". (quando o usuário clica no botão "permitir certificação, aparecerão as opções de certificação")

Observações: 

Um determinado professor/coordenador ou administrador deve poder setar um certificado por turma. Ele deve poder abrir uma turma e dizer que a turma é de certificação. Ao concluir o curso (alcançando o percentual mínimo de realização), o aluno pode solicitar o certificado e o professor pode liberar. 

Essa engine deve funcionar para todos os temas. 

![certificados_timtec](https://cloud.githubusercontent.com/assets/641411/18020113/194ca540-6bb6-11e6-9f8c-3667340e72d4.png)

**Comment by moacirmoda** [comment]
Coloquei toda a regra de negócio dentro do gerenciamento das turmas.

Obs: Para testar turmas que emitam certificados sem progresso mínimo, é necessário ativar a opção, em seguida **logar com o usuário em que se deseja emitir o certificado e avançar no progresso do curso**. Isso acontece porque o certificado é criado no momento em que é registrado o progresso de um usuário. Em produção, será preciso criar esses certificados via command line para os usuários já cadastrados.

**Comment by intrepidocabral** [comment]
Fiz os testes e evidenciei o seguinte:
- O link não está sendo redirecionado para o Certificado e sim para o Atestado de horas. 
  Esse é o certificado (ver abas): http://timtec.conexaobrasil.org/admin/course/1/certificatesettings/
  ![selecao_040](https://cloud.githubusercontent.com/assets/641411/19283818/c845e868-8fc9-11e6-9f0a-22b500761703.png)
- Com o usuário superadmin, não rolou de permitir o certificado, quero dizer, só puder liberar um certificado quando o usuário era da categoria estudante. Eu deveria conseguir emitir o certificado para quaisquer usuários na turma sob as mesma condições. Aqui, no exemplo, tenho dois users na turma, sendo que o primeiro é admin e o segundo é estudante. O primeiro não consigo liberar certificados para ele, só o segundo, e ambos estão matriculados no curso. 
  ![selecao_039](https://cloud.githubusercontent.com/assets/641411/19283798/b27a87be-8fc9-11e6-95e8-d3a99868ae28.png)
- Layout quebrado no mobile:
  ![download 3](https://cloud.githubusercontent.com/assets/641411/19283691/39dd5e1c-8fc9-11e6-8607-31d3565e6b6c.png)
  ![download 4](https://cloud.githubusercontent.com/assets/641411/19283758/7c65b55e-8fc9-11e6-8550-c557b2ebbf4d.png)

**Comment by moacirmoda** [comment]
> Com o usuário superadmin, não rolou de permitir o certificado, quero dizer, só puder liberar um certificado quando o usuário era da categoria estudante. Eu deveria conseguir emitir o certificado para quaisquer usuários na turma sob as mesma condições. Aqui, no exemplo, tenho dois users na turma, sendo que o primeiro é admin e o segundo é estudante. O primeiro não consigo liberar certificados para ele, só o segundo, e ambos estão matriculados no curso.

Não existe esta relação com o role. O que acontece aqui é que o gatilho para a criação do certificado é executado no momento em que um estudante avança seu progresso no curso. Esse momento se dá na finalização de um vídeo, ou, no momento de envio de uma resposta de atividade. Os checkboxes desabilitados se dão pois não existe certificado criado para este usuário. Na prática, indica que o usuário não avançou em nada no curso. Esta regra vale para usuários novos. Para os usuários antigos da plataforma, o certificado ainda não havia sido criado pois não havia sido atingido o progresso mínimo. Esta regra agora mudou: os certificados são criados no primeiro momento do avanço do curso, e eles são exibidos ou não conforme as regras setadas na turma.
Eu loguei com o usuário _felipecabrallafabbrica_ (troquei a senha para "felipecabrallafabbrica"), avancei no curso, e agora a opção está liberada, conforme print abaixo:

![selecao_012](https://cloud.githubusercontent.com/assets/549428/19351086/b37d49ea-9130-11e6-9ef2-3950caf161cc.png)

> O link não está sendo redirecionado para o Certificado e sim para o Atestado de horas. 

Isto depende de a opção de certificado estar marcada ou não. No caso, a opção não está marcada, o botão de certificado está cinza. O resultado é este:

![selecao_014](https://cloud.githubusercontent.com/assets/549428/19351175/15b3ad48-9131-11e6-8c15-3b0cbfc75264.png)

Agora, quando marcamos a opção certificado e salvamos:

![selecao_015](https://cloud.githubusercontent.com/assets/549428/19351215/37d42344-9131-11e6-87a3-8efcd0e3a669.png)

Clicamos no botão verde (que indica que trata-se de um certificado, e não de um atestado de horas) e temos o seguinte resultado:

![selecao_016](https://cloud.githubusercontent.com/assets/549428/19351264/6703cb74-9131-11e6-9bda-94e9b8635c53.png)

> Layout quebrado no mobile

Não cheguei a mexer em nada na opção de criação de certificado. Você acha que existe mesmo a necessidade de investirmos tempo e esforços para adaptar este recurso para mobile? Estamos falando de um recurso exclusivo dos administradores da plataforma e eu não vejo uma situação em que eles queiram editar o layout do certificado de um curso através de um mobile. O que você acha?

**Comment by intrepidocabral** [comment]
> Não existe esta relação com o role. O que acontece aqui é que o gatilho para a criação do certificado é executado no momento em que um estudante avança seu progresso no curso. Esse momento se dá na finalização de um vídeo, ou, no momento de envio de uma resposta de atividade. Os checkboxes desabilitados se dão pois não existe certificado criado para este usuário. Na prática, indica que o usuário não avançou em nada no curso. Esta regra vale para usuários novos. Para os usuários antigos da plataforma, o certificado ainda não havia sido criado pois não havia sido atingido o progresso mínimo. Esta regra agora mudou: os certificados são criados no primeiro momento do avanço do curso, e eles são exibidos ou não conforme as regras setadas na turma.

Fiz o teste com outro usuário e o problema parecia persistir. Avancei mais no curso e depois foi liberado o certificado corretamente.  Eu havia colocado um curso com 1% de carga horária mínima e mesmo assim o problema persistiu. Só foi liberado depois de 50% de realização e depois de alguns f5. Não rolou um realtime, teve um delay. Talvez seja cache... de qualquer modo parece estar funcionando! 

Evidenciei um problema: o botão de baixar o certificado está com problemas. Não está gerando o pdf.

![selecao_044](https://cloud.githubusercontent.com/assets/641411/19357396/dd869590-9147-11e6-84e8-680c37a7b409.png)

> Não cheguei a mexer em nada na opção de criação de certificado. Você acha que existe mesmo a necessidade de investirmos tempo e esforços para adaptar este recurso para mobile? Estamos falando de um recurso exclusivo dos administradores da plataforma e eu não vejo uma situação em que eles queiram editar o layout do certificado de um curso através de um mobile. O que você acha?

Acho que não é uma prioridade agora, mas no futuro é importante que exista essa compatibilidade com layout mobile sim. Vou abrir uma nova issue e jogar isso para o backlog, deixando isso bem para o final. =)

**Comment by moacirmoda** [comment]
- [x] Quando for atestado de horas, para exibição automatica, o estudante deve apenas ter atingido o mínimo _obrigatoriamente_. Somente considerar exibir sem mínimo atingido se for _certificado_ e a opção de turma para emitir certificados sem mínimo requerido estiver habilitada.
- [x] Retirar o momento da criação do CourseCertification do model StudentProgress e adicionar no momento em que um CourseStudent for criado. Não analisar condição do user_can_certificate para a criação. Analisar esta condição somente para a exibição do certificado.
- [x] Criar migration que lista os CourseStudent que não possuem CourseCertification e os cria. (https://docs.djangoproject.com/pt-br/1.10/topics/migrations/#data-migrations)

**Comment by intrepidocabral** [comment]
ótimo! Só precisamos testar agora zerando um ambiente de testes e fazendo o update.

**Comment by moacirmoda** [comment]
- [x] **bug:** o atestado de horas deve ser exibido independentemente se a turma permite certificação ou não.
- [x] **bug:** Meus Cursos > Meus Comprovantes: o usuário está visualizando todos os certificados criados, quando na verdade deveria ver somente os certificados que estão habilitados a serem exibidos.
- [x] **bug:** no tema timtec, não deve permitir certificação.

**sugestão:** Criar uma flag no banco que diz se o certificado pode ou não ser exibido e manipulá-la de acordo com as configurações das turmas e de certificação.
