### ISSUE TITLE
Fórum: melhorias de usabilidade

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#29]
Atualmente o sistema de fórum funciona da seguinte forma: cada curso possui um fórum e os fóruns podem ser organizados por turma. Cada "forum" pode ter diversos tópicos e todo usuário pode abrir um tópico. 
- [x] Paginação: página deve conter apenas os 10 últimos registros. O resto deve ser organizado com paginação. Atualmente não há paginação, o que dificulta muito e acaba pesando a página. Ex. atual sem paginação: http://mooc.timtec.com.br/course/html5/lesson/internet-e-web/#/1
  ![paginacao](https://cloud.githubusercontent.com/assets/641411/18286118/cacfa648-7447-11e6-8af3-a087ab2b615f.png)
- [ ] Busca textual: o usuário deve ter a possibilidade de digitar um termo e pesquisar nos títulos e/ou conteúdo dos tópicos
  ![forum-search](https://cloud.githubusercontent.com/assets/641411/18286179/1748dfd0-7448-11e6-92f0-159b53f18d8e.jpg)
- [x] Edição: administradores devem ter possibilidade de editar respostas e/ou ocultar/deletar respostas/tópicos de terceiros
  ![selecao_029](https://cloud.githubusercontent.com/assets/641411/18287266/c916bde6-744c-11e6-9e9d-baa41847223d.png)
- [x] Multiplas respostas: atualmente um usuário só pode responder a um determinado tópico uma única vez. Isso é um erro. Mesmo respondendo a um tópico
  ![selecao_030](https://cloud.githubusercontent.com/assets/641411/18287328/1358d916-744d-11e6-9d43-a0ef8be04c11.png)
- [x] Seguir publicação: todo tópico deve ter a opção de "seguir publicação". Quando essa opção for setada, o usuário deve receber um email para cada nova postagem feita naquele tópico
  ![selecao_027](https://cloud.githubusercontent.com/assets/641411/18287334/1b71ed90-744d-11e6-81b4-9ffc4ff291a1.png)
- [x] Atualmente os tópico pode receber um rating com seta para cima e para baixo. Substituir isso por like / dislike. Ex.: 
  ![33ac6ab875c33697b27e048f5e6d5bca](https://cloud.githubusercontent.com/assets/641411/18287449/954a9b80-744d-11e6-89e2-887d353bafab.png)
- [x] Na atual listagem de tópicos, só é possível filtrar por "mais recentes", "mais votadas" e "mais respondidas". Seria importante que informações como visualização do tópico e número de respostas estivesse presente na listagem. 

![unnamed](https://cloud.githubusercontent.com/assets/641411/18287662/6e30d996-744e-11e6-878d-ecaf676dfe63.jpg)

**Comment by moacirmoda** [comment]
@robertkapa estas alterações do fórum devem ser feitas antes ou depois da v4? Eu recomendaria deixar esta alteração para a v4 e reestruturar totalmente, baseado nas alterações do hacklab para o paralapraca, o que acha?

**Comment by moacirmoda** [comment]
Analisar e aplicar o django-discussion.

**Comment by moacirmoda** [comment]
forum consertado para a v4.

**Comment by moacirmoda** [comment]
criada a paginação, alterando toda a engine de pagination, filter e ordering para server side.

**Comment by moacirmoda** [comment]
implementada a busca na questão (título e texto), e nas respostas.

**Comment by moacirmoda** [comment]
permitida mais de uma resposta por usuário.

**Comment by moacirmoda** [comment]
em questões: transformado votos em likes e unlikes e adicionando a visualização no template question.html

**Comment by moacirmoda** [comment]
trocado votos por like e unlike.

**Comment by moacirmoda** [comment]
- criado mecanismo de armazenamento de visualizações por usuário.
- criado filtro por mais visualizados.

Cada visualização se mantem por 1 hora. Por exemplo: O usuário **moacir** visualiza uma questão as 12:00, as 12:30 e as 13:20. Serão contabilizadas 2 visualizações.

**Comment by moacirmoda** [comment]
- [x] função de editar pergunta
- [x] função de editar resposta 
- [x] função de esconder resposta

**Comment by moacirmoda** [comment]
> Seguir publicação: todo tópico deve ter a opção de "seguir publicação". Quando essa opção for setada, o usuário deve receber um email para cada nova postagem feita naquele tópico

Qual a real necessidade e importância desta funcionalidade? Pergunto isso pois imagino que o modo certo de se fazer isso seria assincronamente, para evitarmos lentidão. A implementação dessa assincronicidade seria custosa para atualização de todos os IFs, pois teriamos que instalar o RabbitMQ + Celery, adicionar o celery no supervisor, etc, etc.

Dou como sugestão criar um ProfessorMessage, que resultará em um alerta no menu Mensagens, porém, sem enviar email. O que acham?

**Comment by moacirmoda** [comment]
Desenvolvida funcionalidade que, se o usuário solicitar seguir aquela questão, cria uma ProfessorMessage no momento que houver uma nova resposta.

![image](https://cloud.githubusercontent.com/assets/549428/22269151/5e49b0ac-e271-11e6-950f-72dee7b5f34f.png)
![image](https://cloud.githubusercontent.com/assets/549428/22269170/6f2319c2-e271-11e6-8779-e94ca293cc7e.png)

![image](https://cloud.githubusercontent.com/assets/549428/22269181/7ab7ac4e-e271-11e6-98f0-9ec38e79eb03.png)

**Comment by intrepidocabral** [comment]
@moacirmoda testei os itens abaixo com sucesso, mas a busca textual não foi implementada. 

- [x] Paginação
- [x] Busca de texto livre
- [x] Multiplas respostas
- [x] Seguir publicação
- [x] like/dislike
- [x] filtro

**Comment by moacirmoda** [comment]
> @moacirmoda testei os itens abaixo com sucesso, mas a busca textual não foi implementada.

@robertkapa Está implementado sim. No ambiente `http://timtec.dev.timtec.com.br`:
![image](https://cloud.githubusercontent.com/assets/549428/22786173/94ddbb6e-eebe-11e6-8446-dcfebc0a24a6.png)

**Comment by intrepidocabral** [comment]
ok
