### ISSUE TITLE
Página de Criação de cursos - Popup ou warning de saída

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#3]
[importante] Na página de criação de curso o usuário pode sair ou fechá-la a qualquer momento e, se ele não tiver salvado, todas as alterações serão perdidas, pois não existe nenhuma mensagem perguntando se o usuário tem certeza que quer sair e dizendo que ele vai perder tudo, inclusive o curso, não só suas informações. Colocar um pop-up avisando o usuário será de extrema utilidade. 

Página de criação do curso com tema default

![selecao_015](https://cloud.githubusercontent.com/assets/641411/17603434/6e2aedae-5fe7-11e6-813a-c04172265f56.png)

**Comment by intrepidocabral** [comment]
A mensagem está em inglês. Deveria vir em português. 

![selecao_050](https://cloud.githubusercontent.com/assets/641411/19446121/12dc48e4-9476-11e6-969b-5ac22dbe32ef.png)

**Comment by moacirmoda** [comment]
Esta tradução está no JS, preciso ver com o @brunosmartin como proceder. Deixando para a próxima release.

**Comment by moacirmoda** [comment]
Na realidade esta mensagem apareceu em inglês pois é default do browser. Testei no meu browser, em português, e não tive maiores problemas.
