### ISSUE TITLE
bug: Em cursos, todas as unidades aparentam que possuem atividades, mesmo as que não possuão.

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#34]
![selecao_002](https://cloud.githubusercontent.com/assets/641411/18877189/cd5bf194-84a2-11e6-8af5-7c3cd44deaaf.png)

**Comment by moacirmoda** [comment]
- [x] **bug:** Ainda está aparecendo que possui exercícios em todas as unidades no modo adm.
