### ISSUE TITLE
Bug: o papel de coordenador (role) não está conseguindo editar cursos nos quais tem propriedade/status de coordenador.

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#37]

**Comment by moacirmoda** [comment]
@robertkapa não consegui reproduzir o erro. Fiz os seguintes passos:
- criei um usuário através do cadastro da plataforma.
- entrei como admin, entrei no curso "Desenvolvimento Web com AngularJS" > Permissões, adicionei o usuário criado como "Professor Coordenador".
- entrei com o usuário criado, fui em Administração, abri o curso, e consegui editar normal.

**Comment by intrepidocabral** [comment]
Não consegui testar pois a edição final de profile está bugada. Ver issue #67

**Comment by moacirmoda** [comment]
Corrigido.

**Comment by intrepidocabral** [comment]
ok! Está funcionando. Apenas um pequeno bug: ao adicionar um usuário para ser coordenador, o email cadastrado não aparece nem na busca de user, nem na listagem.

![selecao_061](https://cloud.githubusercontent.com/assets/641411/21941849/d503a388-d9b1-11e6-9a68-3e78a72dca3d.png)

![selecao_062](https://cloud.githubusercontent.com/assets/641411/21941863/dc2c06c8-d9b1-11e6-9ec7-402557bdeb1a.png)

**Comment by moacirmoda** [comment]
@robertkapa o webservice não trás, imagino que por questões de segurança. Removi a coluna e-mail de ambas as telas.
