### ISSUE TITLE
Bug: Na edição de um curso, imagem destacada (home tumbnail) estoura se não estiver nas proporções adequadas, impedindo o acesso ao botão de trocar imagem

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#38]
Fazer com que a imagem seja cortada automaticamente e colocar uma dica (tip) dizendo ao usuário qual é a medida recomendada. 

Comportamento esperado:
![download 6](https://cloud.githubusercontent.com/assets/641411/19004582/eedf9a0a-872c-11e6-8ef4-444d8314e30a.png)

Exemplo de dica (tip) que deve ser implementada: 

![download 5](https://cloud.githubusercontent.com/assets/641411/19004441/524861cc-872c-11e6-91cc-546be97e0da9.png)

Comportamento com problema no uso de imagens grandes. O que deve ser feito? O sistema deve cropar a imagem para que ela não estoure. 

![download 4](https://cloud.githubusercontent.com/assets/641411/19004324/c1a704ca-872b-11e6-927b-99c97d810b6b.png)

![unnamed 1](https://cloud.githubusercontent.com/assets/641411/19004470/68d29f34-872c-11e6-85f6-9931f599d183.png)

**Comment by moacirmoda** [comment]
@robertkapa Não consegui reproduzir o erro. Executei os seguintes passos:
- Editei um curso, removendo seu vídeo para a thumb poder aparecer (via terminal)
- Subi uma imagem de 1400x788 e ela foi exibida corretamente na home e na listagem de cursos.
- Subi uma imagem de 1304x1800 e ela foi exibida corretamente na home e na listagem de cursos.

**Comment by intrepidocabral** [comment]
ok! closed.
