### ISSUE TITLE
Bug: Adicionar instrutor já existente em outro curso! 

### ISSUE THREAD

**Issue by Nathlis** [institutotim/timtec#39]
Quando vou procurar um instrutor já existente acontece alguns erros:

**1. Quando vou vincular um professor que já fez um curso na plataforma em outro curso (novo): primeiro tentei procurá-lo pelo nome, mas não funciona. (Isso é ruim porque nem sempre eu sei como foi o usuário do professor)** 

![procura por nome](https://cloud.githubusercontent.com/assets/18741130/19049212/da1c7d18-897f-11e6-9f62-b2dbf128ceb1.png)

**2. Depois tentei procurar pelo usuário, dessa forma dá certo, porém não aparece nenhuma informação como nome, foto e biografia.**

![procura por usuario](https://cloud.githubusercontent.com/assets/18741130/19049265/14ebe9a6-8980-11e6-9af6-fee8bbe14b35.png)

![por usuario apos salvar](https://cloud.githubusercontent.com/assets/18741130/19049272/1a634352-8980-11e6-84f6-ae51807b6e61.png)

**3. Mas temos uma exceção, com o Edu Agni (usuário eduagni) funciona:**

![edu excecao](https://cloud.githubusercontent.com/assets/18741130/19049302/3c28091e-8980-11e6-99cb-b97da804f619.png)

**Comment by intrepidocabral** [comment]
resolvido.
