### ISSUE TITLE
Bug: layout mobile do certificado e atestado de horas.

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#41]
ver issue #27

**Comment by moacirmoda** [comment]
@robertkapa qual bug é este mesmo? Vi o #27 e não consegui identificar.

**Comment by intrepidocabral** [comment]
No ambiente mobile não é possível ter acesso ao certificado. O mesmo aparece, mas fica totalmente quebrado. Sugiro que no mobile (em especial dispositivo sm, isto é, smarthphone) apareça o botão download e o usuário possa fazer o download do pdf. 

![imagem da pagina 2017-02-07 - 16 54 03](https://cloud.githubusercontent.com/assets/641411/22706362/1b907e68-ed56-11e6-9ba6-39a1ee5b5193.png)
![imagem da pagina 2017-02-07 - 16 53 27](https://cloud.githubusercontent.com/assets/641411/22706363/1f5d325c-ed56-11e6-9aa0-d5bb6a8e3247.png)

**Comment by moacirmoda** [comment]
Ajustado

**Comment by intrepidocabral** [comment]
![imagem da pagina 2017-02-13 - 13 59 07](https://cloud.githubusercontent.com/assets/641411/22890963/f6faf684-f1f4-11e6-96c7-e72deae9aea1.png)

![imagem da pagina 2017-02-13 - 14 19 33](https://cloud.githubusercontent.com/assets/641411/22891755/79a1b72e-f1f7-11e6-9cf1-c7c4867201e4.png)


O download do certificado está bugado. Quando clico para baixar, cai nessa página.

**Comment by moacirmoda** [comment]
@robertkapa qual o curso e qual o usuário que você está tentando baixar o certificado. Temos um bug no qual existem alguns usuários que estão no curso mas não possuem Class, por isso preciso saber essa info.

**Comment by moacirmoda** [comment]
Verificar com infos do issue #90

**Comment by moacirmoda** [comment]
Corrigido no ajuste do bug #90.
