### ISSUE TITLE
Fazer um changelog das mudanças da 3.2 para 3.3

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#42]

**Comment by intrepidocabral** [comment]
Segue Changelog: 

---

# Modificações realizadas versão 3.3

### Página de Criação de cursos
- Inserido uma mensagem (warning) contra fechamento automático. Caso não tenha salvo as modificações , um usuárioadmin recebe uma mensagem pergunta de confirmação antes de fechar a página do browser;
  ![selecao_050](https://cloud.githubusercontent.com/assets/641411/19448718/ca1b32a8-9481-11e6-8b15-4a13af8b85e8.png)
  Ref.: https://github.com/institutotim/timtec/issues/3

### Página de Turmas
- Melhoria na engine de turmas de um curso: agora é possível buscar alunos por email, nome e username;
- Melhor integração com sistema de certificados;
  ![selecao_051](https://cloud.githubusercontent.com/assets/641411/19448887/5d23b214-9482-11e6-959c-87c61ec42a9f.png)
  Ref.: https://github.com/institutotim/timtec/issues/26

### Página do curso
- Inserido de nome da turma vigente;
  ![selecao_048](https://cloud.githubusercontent.com/assets/641411/19448909/71bfad86-9482-11e6-8f85-6fdcfbd985fb.png)
  Ref.: https://github.com/institutotim/timtec/issues/5

### Página do Perfil e Cadastro do Usuário
- Mudança de nome do menu para "Minha Área";
- Inserido visualização de todos os campos que estão no cadastro;
- Login com email e username;
- Inserido no cadastro inicial "primeiro nome", "sobrenome", "estado" e "cidade" como campos obrigatórios;
- Inserido no cadastro interno, "data de nascimento," "redes sociais" como campos não obrigatórios (facebook, twitter, whatsapp[campo de telefone com ddd], telegram);
  ![download](https://cloud.githubusercontent.com/assets/641411/19449035/c3c68c30-9482-11e6-8aa2-ff92c4d48561.png)
- Ref.: https://github.com/institutotim/timtec/issues/4
- Ref.: https://github.com/institutotim/timtec/issues/10
- Ref.: https://github.com/institutotim/timtec/issues/40

### Página de Anotações
- Reformulada;
  ![selecao_052](https://cloud.githubusercontent.com/assets/641411/19449079/ee59f3d8-9482-11e6-8d73-b3aa3b8efff0.png)
  ![selecao_053](https://cloud.githubusercontent.com/assets/641411/19449099/ffe2d516-9482-11e6-9b51-37d09ffd2b84.png)
  Ref.: https://github.com/institutotim/timtec/issues/11

### Página de Mensagens
- Reformulada;
  ![selecao_055](https://cloud.githubusercontent.com/assets/641411/19449285/b56d0c80-9483-11e6-8573-3b64fcd65cee.png)
  ![selecao_054](https://cloud.githubusercontent.com/assets/641411/19449288/ba323c0e-9483-11e6-88f8-51ced3a084e3.png)
  Ref.: https://github.com/institutotim/timtec/issues/17

### Emissão de Certificados
- Reformulado sistema de emissão de certificados;
- Permissão de emissão de certificados sem necessidade de conclusão completa de tempo mínimo do curso;
  ![selecao_051](https://cloud.githubusercontent.com/assets/641411/19449322/ddb2885a-9483-11e6-85ef-e1b7df32af10.png)
  Ref.: https://github.com/institutotim/timtec/issues/27

# Bugs corrigidos na versão 3.3

### Página Forbiden
- Implementada uma página de erro para resultado 404 e 500
  ![selecao_056](https://cloud.githubusercontent.com/assets/641411/19449386/28bdb0ea-9484-11e6-9656-75c3e017a117.png)
  Ref.: https://github.com/institutotim/timtec/issues/18

### Favicon
- Inserido favicon nos temas
  Ref.: https://github.com/institutotim/timtec/issues/14

### Bug mobile: status do curso visível ao usuário sem permissão

Ref.: https://github.com/institutotim/timtec/issues/15

### Bug em atividades, no modo "true or false"
- Inserido warning quando alguma alternativa não for preenchida;
- Inserido opção de feedback personalizado;
  Ref.: https://github.com/institutotim/timtec/issues/20
  Ref.: https://github.com/institutotim/timtec/issues/22

### Bug: usuário já registrado com acesso a página de aceitação de termos de uso

Ref.: https://github.com/institutotim/timtec/issues/21

### Bug: template timtec
- Visibilidade ruim do botão "ir para o curso";
- Retirado box "Professor, entre em contato"

Ref.: https://github.com/institutotim/timtec/issues/23

Ref.: https://github.com/institutotim/timtec/issues/30

### Bug: icone de unidades
- Unidades com atividades devem ter ícone indicando presença de atividade. Unidades sem atividade não devem conter ícones; 
  Ref.: https://github.com/institutotim/timtec/issues/34
