### ISSUE TITLE
Email de boas vindas - entrada no curso

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#43]
Cada curso deve ter um local onde o professor-criador do curso (administrador) escreve um email de boas-vindas automático para os alunos. Este email deve ser enviado automaticamente quando um aluno se inscreve no curso. 

- [x] Criar form de escrita do email na edição do curso com label "Email de boas-vindas". A tip deverá ser "Este email é enviado aos alunos que se inscrevem no curso automaticamente no ato da inscrição";
- [x] Criar engine de envio de email;

**Comment by intrepidocabral** [comment]
Email de boas vindas recebido com sucesso. Precisa de correção no formato do email recebido. 

![selecao_021](https://cloud.githubusercontent.com/assets/641411/22021151/c9c20f34-dca2-11e6-8641-252075a16da0.png)

**Comment by moacirmoda** [comment]
> Email de boas vindas recebido com sucesso. Precisa de correção no formato do email recebido.

Resolvido

![image](https://cloud.githubusercontent.com/assets/549428/22333519/c58d8750-e3bd-11e6-8b8f-5c3e97623d2a.png)
