### ISSUE TITLE
Tela de turmas - inserir data de inscrição no curso

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#44]
Quando um aluno se matricula no curso, o professor não consegue saber quando esse aluno se inscreveu observando as turmas deste curso. 
- [x] Acrescentar a coluna "data de matricula" no formato "dd/mm/yyyy  - hh:mm" nesta tela (tela de turma de um curso). É interessante que a coluna possa ser dinâmica, isto é, ao clicar no título da coluna ela deve organizar por ordem crescente ou decrescente. 

http://timtec.conexaobrasil.org/class/2/

**Comment by moacirmoda** [comment]
Bruno colocou na v4.0. Analisar e aplicar.

**Comment by moacirmoda** [comment]
Feito

**Comment by intrepidocabral** [comment]
Não consegui testar. Depende da issue #70

**Comment by intrepidocabral** [comment]
testado e aprovado!
