### ISSUE TITLE
Inserir botão para sair do curso

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#46]
Por hora não há opção do aluno "sair" de um curso. Para o professor, talvez seja interessante saber desse registro de desistência. Ao cancelar a inscrição, poderia aparecer um questionário, perguntando os motivos. Isso pode ser usado para melhorar o curso.

Esse poderia ser um dado adicional sobre o curso: pessoas que manifestaram desejo explícito de não continuar o curso.

Agora, o aluno pode manifestar interesse e depois voltar a refazer o curso. Isso também pode acontecer.

**Comment by moacirmoda** [comment]
Criado uma flag em CourseStudent chamada is_active, que pode ser True ou False. Esta flag indica se o estudante está ativo no curso ou não. 

Foi criado um botão "Sair do curso", que inativa esta flag. Para o estudante, o comportamento do sistema é de como se ele nunca tivesse participado do curso, porém, o CourseStudent continua criado. Assim é possível listar os desistentes.
