### ISSUE TITLE
Criar subdomínios timtec.dev.timtec.com.br e if.dev.timtec.com.br e apontar para server de teste

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#47]
- [x] Criar sub-domínios e apontar para servidor de homologação (felipe)
- [ ] Apontar branch dev para cada sub-domínio
- [ ] Settar respectivos temas para cada sub-domínio. Um deve atender ao atual tema dos ifs e outro ao atual tema timtec

**Comment by intrepidocabral** [comment]
foram criados os dois sub-domínios e apontados para a máquina: 

* timtec.dev.timtec.com.br
* if.dev.timtec.com.br

foram também criados os users:
- timtec-dev-timtec
- timtec-dev-if

Cada user desse deve controlar uma instalação e um respectivo tema.

**Comment by moacirmoda** [comment]
- criar os seguintes domínios, correspondendo aos usuários
  - timtec.homolog.timtec.com.br, timtec-homolog-timtec
  - if.homolog.timtec.com.br, timtec-homolog-if

Apontar para a mesma máquina do servidor de dev, com IP 45.33.77.217.
