### ISSUE TITLE
Fazer deploy de teste para validar o merge da 3.3 com a 4.0

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#49]

**Comment by moacirmoda** [comment]
fiz algumas alterações nos migrations do core, corrigindo e mergeando algumas migrations.

**Comment by moacirmoda** [comment]
@robertkapa Fiz um deploy da 4.0 no endereço if.dev.timtec.com.br

**Comment by intrepidocabral** [comment]
ok!
