### ISSUE TITLE
[importante] O aluno não consegue saber em qual turma está inscrito.

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#5]

**Comment by intrepidocabral** [comment]
Fiz um teste a a turma em questão não bate com a turma na qual o aluno realmente está. 

![selecao_047](https://cloud.githubusercontent.com/assets/641411/19445792/8f968edc-9474-11e6-94b2-8c39698f7e46.png)

**Comment by intrepidocabral** [comment]
Recomendado: 

![selecao_048](https://cloud.githubusercontent.com/assets/641411/19445937/2b741be4-9475-11e6-931d-0011d412d288.png)

**Comment by moacirmoda** [comment]
não consegui reproduzir em ambiente dev e ambiente teste.

**Comment by intrepidocabral** [comment]
ok, vou explicar novamente. 

Como está atualmente: 
![selecao_060](https://cloud.githubusercontent.com/assets/641411/21939660/f5662f10-d9a7-11e6-877c-52792933c7b3.png)

Como deveria ser (comportamente esperado): 
![2b741be4-9475-11e6-931d-0011d412d288](https://cloud.githubusercontent.com/assets/641411/21939683/1772faac-d9a8-11e6-9876-f5bc3e99de03.png)

Repare que na primeira imagem não há nome do aluno.

**Comment by moacirmoda** [comment]
@robertkapa não havia nenhuma lógica para exibir o nome do usuário. Pode ser que tenha se perdido no meio dos commits. Eu a inseri novamente. Existe uma regra CSS para esconder os labels "Usuário", "Turma" e "Por". Mantive essa regra
