### ISSUE TITLE
BUG: Processo de cursar um curso do início ao fim não funciona

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#50]
ref: #53 

Testar e corrigir também:
- [x] Fazer curso
- [x] Salvar uma nota de uma aula
- [x] Postar questões no Forum
- [x] Responder questões no Forum (está quebrado e se manterá quebrado pois iremos investir tempo nos fóruns novos)
- [x] Acessar o Material Didático
- [x] Receber mensagens dos professores (hoje apenas por email)
- [x] Assistir uma aula
- [x] Responder as atividades

**Comment by moacirmoda** [comment]
@robertkapa o fórum está quebrado.. creio que o melhor é não investir tempo em consertar, já que vamos trocar, certo?

**Comment by intrepidocabral** [comment]
> @robertkapa o fórum está quebrado.. creio que o melhor é não investir tempo em consertar, já que vamos trocar, certo?

Sim, melhor não se preocupar. Mas teremos de prever uma migração do modelo atual para o novo modelo... digo dos dados, as perguntas em aberto.

**Comment by intrepidocabral** [comment]
Bugs encontrados durante a navegação completa de um curso:

- [x] Alguns marcadores do menu de unidades não estão marcados em vermelho mesmo depois que o vídeo da unidade é visto. 
![selecao_051](https://cloud.githubusercontent.com/assets/641411/21901705/f4f970e6-d8df-11e6-80c0-5625741d16e3.png)

- [x] Tive problemas com a apresentação das atividades. Algumas demoraram para carregar, foram apresentadas primeiro quebradas e depois ficaram normais. 

- [x] As atividades são mostradas (showed) inicialmente com mensagem de erro, mesmo sem sequer estarem respondidas. Elas devem vir sem mensagem alguma. 
![selecao_052](https://cloud.githubusercontent.com/assets/641411/21901722/02fa1ad8-d8e0-11e6-837e-9de8e7f5e902.png)

- [ ] os links de materiais complementares quebraram. Eles não aparecem mais como links. 
![selecao_053](https://cloud.githubusercontent.com/assets/641411/21901749/1b83dee0-d8e0-11e6-82f1-b56e528b83ce.png)

**Comment by moacirmoda** [comment]
@robertkapa 

> Alguns marcadores do menu de unidades não estão marcados em vermelho mesmo depois que o vídeo da unidade é visto.

No teste que eu fiz, correu certo. Veja a screenshot:

![image](https://cloud.githubusercontent.com/assets/549428/22003817/c3f6d2d4-dc3d-11e6-9525-11fe614570d4.png)

**Comment by moacirmoda** [comment]
> Tive problemas com a apresentação das atividades. Algumas demoraram para carregar, foram apresentadas primeiro quebradas e depois ficaram normais.

Isso creio ser lentidão do servidor. Não tem muito o que fazer.

**Comment by moacirmoda** [comment]
>  As atividades são mostradas (showed) inicialmente com mensagem de erro, mesmo sem sequer estarem respondidas. Elas devem vir sem mensagem alguma.

Corrigido.

**Comment by moacirmoda** [comment]
> os links de materiais complementares quebraram. Eles não aparecem mais como links.

Preciso perguntar para o pessoal do hacklab como resolver isso. Parece que a lib foi desenvolvida in house.

**Comment by intrepidocabral** [comment]
> > os links de materiais complementares quebraram. Eles não aparecem mais como links.

> Preciso perguntar para o pessoal do hacklab como resolver isso. Parece que a lib foi desenvolvida in house.
Talvez o @GustavoVS ou o @brunomatins saibam...

**Comment by moacirmoda** [comment]
@robertkapa afinal, qual será a medida para isso?
