### ISSUE TITLE
criar a perspectiva de tema para aplicação

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#52]
Toda vez que são feitas modificações no templates são feitas, a atualização sobreescrever. Pensar uma forma de superar essa dimensão.

**Comment by moacirmoda** [comment]
Não entendi, @robertkapa

**Comment by intrepidocabral** [comment]
isso daqui está relacionado ao que foi feito com relação a transformar o tema em app. Para propósito do indivíduo que for fazer uma instalação nova, pode ser bem útil. Precisamos documentar melhor o novo sistema de theme e documentar a possibilidade do user extender o theme.
