### ISSUE TITLE
BUG: Gestão de cursos não funciona

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#56]
url: http://localhost:8000/admin/courses/
ref: #53 

Testar e corrigir também:
- [x] Criar cursos
- [x] Acesso aos relatórios de gestão (Tela de relatórios de gestão)
- [ ] ? Número de usuário que terminaram pelo menos um curso.
- [ ] ? Porcentagem de alunos alunos atualizaram o perfil com mais informações depois do primeiro cadastro
- [x] Publicar (e mudar o status) dos cursos
- [x]  Definir data de início de um curso
- [x] Editar todos os campos da introdução dos cursos e das aulas
- [x] Criar Unidades, vídeos e atividades
- [x] Acesso aos relatórios de gestão (Tela de relatórios de gestão) do curso para todas as turmas

**Comment by moacirmoda** [comment]
@robertkapa você sabe como faço para simular os passos que marquei com um "?"?

**Comment by robertkapa** [comment]
Salve @moacirmoda os relatórios atuais são esses: http://docs.timtec.com.br/manual_professor/estatisticas.html?highlight=curso

**Comment by intrepidocabral** [comment]
Tentei testar o item 1 (criar cursos), mas deu esse erro (ele simplesmente não salvou). O resto parece estar ok. 

![selecao_047](https://cloud.githubusercontent.com/assets/641411/21893598/c5223424-d8c2-11e6-90cd-97b17f446970.png)

Tb não consegui buscar instrutores na base: 
![selecao_048](https://cloud.githubusercontent.com/assets/641411/21893618/dc32f0d6-d8c2-11e6-8126-82ed7ebe03bd.png)

**Comment by moacirmoda** [comment]
Erro ao salvar e erro no auto-complete corrigidos.

**Comment by intrepidocabral** [comment]
Salve @moacirmoda 

1 - Quanto aos relatórios, os relatórios atuais são esses: http://docs.timtec.com.br/manual_professor/estatisticas.html?highlight=curso
2 - Quanto ao segundo item (? Porcentagem de alunos alunos atualizaram o perfil com mais informações depois do primeiro cadastro), não é possível fazer isso no timtec no painel. Onde vc pegou essa info?

**Comment by moacirmoda** [comment]
Salve @robertkapa 

Encontrei essas infos aqui:
https://github.com/hacklabr/timtec/blob/master/docs/Papeis-de-Usu%C3%A1rios.md
