### ISSUE TITLE
BUG: Módulo de mensagens não funciona

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#57]
url: http://localhost:8000/admin/course/1/messages/
ref: #53
ref: #61

**Comment by moacirmoda** [comment]
@robertkapa problema corrigido e envio de e-mail setado para ambos os ambietes. Coloquei uma conta minha.

**Comment by intrepidocabral** [comment]
Deu certo! só que nos títulos dos emails aparece "true". Acredito que era uma palavra de controle. Tem como remover isso? =) 
![selecao_065](https://cloud.githubusercontent.com/assets/641411/22039565/f72fdf8e-dce6-11e6-84ee-0fb8b1d9e1ab.png)

**Comment by moacirmoda** [comment]
Resolvido

![image](https://cloud.githubusercontent.com/assets/549428/22333928/9bcd8882-e3bf-11e6-883a-7729ef09668a.png)
