### ISSUE TITLE
BUG: Relatórios de um curso não funciona

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#59]
url: http://localhost:8000/admin/course/1/reports/
ref: #53 

Testar e corrigir também:
- [x] Análise de progresso no curso por Aluno
- [x] Número total de alunos no curso
- [x] Listagem dos Alunos do curso, com porcentagem de conclusão do curso.
- [x] Porcentagem de conclusão em cada Aula.
- [x] Análise de progresso do curso por Aula
- [x] Lista de aulas do curso, com a porcentagem de alunos que concluiu cada uma.
- [x] Enviar Mensagens para os alunos das suas turmas
- [x] Moderar forum (pode ocultar questões) de suas turmas

**Comment by moacirmoda** [comment]
__!!!__ Verificar se não é simplesmente erro de lentidão do sistema, por carregar todos os usuários de uma vez.

**Comment by intrepidocabral** [comment]
sim, está muito lento. Não tem paginação, né @moacirmoda ?

**Comment by moacirmoda** [comment]
@robertkapa não tem.

**Comment by intrepidocabral** [comment]
@moacirmoda tem como colocar uma paginação? Senão fica quase impossível ver os resultados.

**Comment by moacirmoda** [comment]
Paginação adicionada, porém ainda falta descobrir como fazer com a ordernação por progesso, dado que isso é um dado que não está no banco e é formado através de lógica no próprio django.

**Comment by intrepidocabral** [comment]
ok! 

No futuro, temos de pensar melhor esse relatórios.
