### ISSUE TITLE
Inserir conteúdo estático (texto e/ou imagem) para além de vídeos

### ISSUE THREAD

**Issue by Nathlis** [institutotim/timtec#65]
Atualmente só é possível ter nos cursos do TIM Tec conteúdo com VIDEOS do Youtube ou ATIVIDADES. Do ponto de vista de uma ferramenta mooc isso é extremamente limitante e erroneo. Não queremos que funcione dessa forma e essa issue é para resolver esse problema. 

Veja como funciona atualmente: 

1 - O professor/coordenador/administrador ADICIONA UMA NOVA UNIDADE. 
2 - Automaticamente já abre para ele um box com o pedido de um "video da unidade";
3 - A escolha do professor/coordenador/administrador fica restrita a um VÍDEO ou ATIVIDADE (só existem esses dois botões e o conteúdo é restrito a vídeos do youtube)

![selecao_030](https://cloud.githubusercontent.com/assets/641411/22762011/47c7ee0a-ee44-11e6-8fc2-be731daccf6d.png)

Como deve funcionar (solução): 

1 - O professor/coordenador/administrador ADICIONA UMA NOVA UNIDADE e pode escolher que TIPO DE CONTEÚDO ele quer. O professor/coordenador/administrador poderá escolher entre VÍDEO ou TEXTO/IMAGEM. 
2 - A tela deve conter 3 botões: VIDEO, TEXTO/IMAGEM e ATIVIDADE;
3 - Deve ter uma mensagem "Escolha um TIPO DE CONTEUDO" e abaixo os botões VIDEO e TEXTO/IMAGEM
4 - O botão TEXTO/IMAGEM deve apresentar um editor visual (do tipo wyswyg) e deve permitir upload de imagem e edição html, conforme exemplo abaixo. 

![selecao_031](https://cloud.githubusercontent.com/assets/641411/22762179/31c88708-ee45-11e6-9818-ecaea95b2236.png)

![selecao_032](https://cloud.githubusercontent.com/assets/641411/22762182/38f8013e-ee45-11e6-87fb-69f54dcfefc0.png)

**Comment by moacirmoda** [comment]
@Nathlis vc tem algum link onde eu possa ver essa nova implementação ao vivo?

@robertkapa você pode me ajudar com essa questão?

**Comment by Nathlis** [comment]
@moacirmoda link para ser visto em mooc.timtec.com.br

[http://mooc.timtec.com.br/course/mooc-e-novas-formas-de-aprendizagem/lesson/aula-4-dicas-para-engajar-os-estudantes/#/2](url)

**Comment by moacirmoda** [comment]
@robertkapa não me lembro qual foi a resolução que tomamos para isso.

**Comment by moacirmoda** [comment]
Foi decidido que nos reuniremos com hacklab e mupi para entendermos melhor a demanda e conseguirmos avançar com clareza.

**Comment by robertkapa** [comment]
@moacirmoda apaguei os comentários antigos desse item e reescrevi junto com a @Nathlis a fim de ficar mais fácil a compreensão do que é essa issue.

**Comment by intrepidocabral** [comment]
@moacirmoda apaguei os comentários antigos desse item e reescrevi junto com a @Nathlis a fim de ficar mais fácil a compreensão do que é essa issue.

**Comment by moacirmoda** [comment]
Foi criado um novo botão "Texto/Imagem" (ainda vou traduzir) que possibilita colocar informações em um box tinyMCE:
![selecao_003](https://cloud.githubusercontent.com/assets/549428/22794445/5f59121a-eeda-11e6-9087-d066924f307c.png)

Este é o resultado:
![selecao_004](https://cloud.githubusercontent.com/assets/549428/22794616/e99d05a8-eeda-11e6-94cb-ff96b0a232d8.png)

Estes dois botões Vídeo / Texto só aparecerão quando tanto vídeo quanto texto/imagem forem preenchidos. Do caso contrário, o sistema saberá identificar o que mostrar.

**Comment by intrepidocabral** [comment]
@moacirmoda esse editor está muito simplificado. Não tem opção de upload de imagem nele... Precisa alterar isso, ampliar as possibilidades de edição e colocar upload de imagem.  Repare que o editor do exemplo é mais rico.

**Comment by moacirmoda** [comment]
Adicionei todas as opções do TinyMCE:
![image](https://cloud.githubusercontent.com/assets/549428/23102814/ba82038e-f68e-11e6-9a65-76cdd792e596.png)

**Comment by intrepidocabral** [comment]
Problemas encontrados: 
- [ ] O campo "insert/edit image" do editor não está deixando escrever a "image description";
- [ ] O campo "insert/edit image" do editor não está deixando escrever as "dimensions";
- [ ] Quando faço a inserção de uma imagem maior do que o tamanho do conteiner, na view do curso, o layout explode. **É preciso que o conteúdo de TEXTO/IMAGEM seja limitado por largura e altura!** Caso contrário vai estourar e quebrar o layout da view. Se está usando bootstrap, basta colocar um conteiner e uma row para limitar, ou algo parecido, não sei dizer, tem que analisar o código da view mas creio que é algo simples. 

Veja o comportamento desses bug nesse video: https://youtu.be/WsybHBFsPDI

Essa dimensão deve ser preservada quando o conteúdo não for vídeo: 

![captura de tela de 2017-02-19 18 27 16](https://cloud.githubusercontent.com/assets/641411/23106202/18bcbf9a-f6c9-11e6-83e3-daa34817f959.png)

**Comment by moacirmoda** [comment]
Corrigido:

![image](https://cloud.githubusercontent.com/assets/549428/23166187/5a761c64-f81e-11e6-97fb-eed4dbfeb3bc.png)

O problema da dimensão se corrige da seguinte forma: quando uma imagem maior é inserida, o próprio TinyMCE calcula a melhor dimensão.

**Comment by intrepidocabral** [comment]
@moacirmoda ainda continua com problema. Coloquei essa imagem e ela explode a view: http://if.dev.timtec.com.br/media/boas-praticas-em-desenvolimento-de-software/DSC00088.JPG

A view tem que pegar tudo que tá dentro dela e conteinerizar para que imagens grandes não explodam tudo. 
![timtec](https://cloud.githubusercontent.com/assets/641411/23178700/314e9c40-f84a-11e6-9b52-df97dfca87da.jpg)

**Comment by moacirmoda** [comment]
Decidimos encerrar esse issue.
