### ISSUE TITLE
bug: página de cadastro

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#66]
![selecao_039](https://cloud.githubusercontent.com/assets/641411/21395468/bd6d7554-c783-11e6-830b-a8872e9803f8.png)

![selecao_040](https://cloud.githubusercontent.com/assets/641411/21395756/dfef00f6-c784-11e6-94af-5af659a6c569.png)

**Comment by moacirmoda** [comment]
@robertkapa ambos os problemas foram resolvidos. 

Temos um detalhe aqui: No `settings_local.py` é necessário incluir o tema que será utilizado, com o append na tupla abaixo:
```
INSTALLED_APPS += (
    'if_theme',
)
```

Além disso, é necessário alterar a variável `TIMTEC_THEME` para o mesmo nome do template, no caso. `if_theme`.

Creio que isso seja necessário documentar na instalação. Você faz isso?

**Comment by intrepidocabral** [comment]
Olá @moacirmoda!

Fiz uma alteração aqui (https://github.com/hacklabr/timtec/blob/master/docs/instalacao_e_configuracao/Configura%C3%A7%C3%B5es.md), mas não tenho certeza de tudo que isso envolve.  Preciso documentar melhor na documentação de deploy. 

Atualmente funciona assim (v3.3): 
- A aplicação já vem com tema;
- O tema é settado no settings_local.py
- Para mudar o tema só preciso alterar o nome da variável TIMTEC_THEME

Como será na versão v4.0:
- A aplicação só virá com tema default;
- Novos temas deverão ser inseridos via app;
- Novos temas deve ter repositório próprio e deve extender o tema default;
- Para usar um novo tema, o desenvolvedor deve abrir o settings_local.py e alterar duas informações: 
a) settar a variável TIMTEC_THEME para o nome do tema;
b) acrescentar essa chave ativando o app:

```
INSTALLED_APPS += (
    'if_theme',
)
```
Seria isso, @moacirmoda ?

**Comment by moacirmoda** [comment]
@robertkapa correto.

**Comment by intrepidocabral** [comment]
feito!
