### ISSUE TITLE
bug: edição de perfil

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#67]
![selecao_041](https://cloud.githubusercontent.com/assets/641411/21396831/a818e97c-c788-11e6-80b8-5ff5b49b4b23.png)

![selecao_042](https://cloud.githubusercontent.com/assets/641411/21396877/d6d44446-c788-11e6-87f2-0fdc57f3ec7e.png)

**Comment by moacirmoda** [comment]
ambos problemas resolvidos.
