### ISSUE TITLE
Bug: rodapé

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#68]

**Comment by moacirmoda** [comment]
@robertkapa poderia explicar com detalhes o que é esse bug?

**Comment by intrepidocabral** [comment]
salve @moacirmoda 

Na verdade não é um bug exatamente... mas o footer está fora do padrão. O correto seria esse daqui: 

![selecao_064](https://cloud.githubusercontent.com/assets/641411/21993644/15ba1c38-dc03-11e6-9c66-31eef65e9271.png)

**Comment by intrepidocabral** [comment]
Aqui está o código que gera esse footer: https://github.com/robertkapa/institutotim-header-footer

Veja aqui o html/css feito com bootstrap: https://github.com/robertkapa/institutotim-header-footer/blob/master/footer_mooc.html

**Comment by moacirmoda** [comment]
Feito.
Faltou colocar os links das redes sociais.

**Comment by intrepidocabral** [comment]
@moacirmoda sim. E faltou linkar certinho algumas coisas. Seria isso daqui: 

- [x] **Conheça TIM Tec** -> url/pages/about
- [x] **Contato** -> linkar para form de contato (ver: https://cloud.githubusercontent.com/assets/641411/22710721/95492c96-ed65-11e6-85e7-a0289738915c.png) 
- [x] **Lista de cursos** -> url/courses
- [x] **Cadastrar perfil** -> url/accounts/signup/
- [x] **Entrar** -> url/accounts/login/
- [x] **Recuperar senha** -> url/accounts/password/reset/

**Comment by moacirmoda** [comment]
Feito.
