### ISSUE TITLE
bug: criação de nova turma dá página de erro

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#70]

**Comment by intrepidocabral** [comment]
veja o comportamento do bug: https://youtu.be/X_FtyBR9ZCU

Edição de turma já existente tb está bugada: https://youtu.be/1E1Zl5_7p9c

**Comment by moacirmoda** [comment]
@robertkapa ambos corrigidos e testados. O bug na verdade era relacionado ao compressor, que parece estar desalinhado, com algum erro de integridade. Imagino que esse erro seja em decorrência das constantes atualizações do ambiente de testes. Como é um erro de ambiente, desabilitei a compressão offline e tudo voltou ao normal.

**Comment by intrepidocabral** [comment]
ok! Parece funcional agora!
