### ISSUE TITLE
bug: inscrição no curso

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#72]
Botões de "inscrever no curso" e "sair do curso" não estão funcionando.

Comportamento esperado ao clicar no botão "continuar curso" (usuário deve ser levado as unidades quando clica nesse botão. Atualmente está bugado para usuários com permissão de admin. Como aluno funciona, mas como admin está bugado):  https://youtu.be/77Txev66o-8

O botão "sair" deve remover o aluno do curso e voltar a página original, como se ele não estivesse inscrito. 

Logado como admin, ao clicar em "continuar curso" ou "sair" nada acontece: https://www.youtube.com/watch?v=queMuFuB74o&feature=youtu.be

**Comment by moacirmoda** [comment]
@robertkapa veja a lógica que exibe o menu do curso ou o botão para se inscrever:

```
{% elif user|is_assistant_or_coordinator:course or user_is_enrolled and course.has_started %}
    {% include "_course-header-inline.html"  with course=course %}
{% else %}
    {% include "_go-to-course-button-inline.html"  with course=course %}
{% endif %}
```

Se o usuário for assistant ou coordinator (usuário admin se encaixa nessas opções), ele vai exibir sempre o menu do curso, como se o usuário estivesse logado. Em outras palavras, pelo o que entendi, nunca houve a opção de um usuário admin se cadastrar em um curso, e também não há a opção de um admin sair de um curso.

**Comment by intrepidocabral** [comment]
@moacirmoda negativo. Antes qualquer usuário conseguia estar inscrito em um curso e acessar as aulas/unidades, perfazendo o curso, contando inclusive com lógica percentual de execução do curso em "meus cursos". Veja vídeo demonstrando esse comportamento, comparando a versão v3.2 com a atual v4: https://youtu.be/re99U7XeYk8

**Comment by moacirmoda** [comment]
@robertkapa 
> Antes qualquer usuário conseguia estar inscrito em um curso e acessar as aulas/unidades, perfazendo o curso, contando inclusive com lógica percentual de execução do curso em "meus cursos". 

Sim, eu entendo isso. O que quero dizer é que não é exibido o botão "Inscrever-se no curso" para usuários que não sejam estudantes. Quando esses usuários assistants ou coordinators acessavam a página do curso, eles já estavam inscritos "automaticamente", entende?

Pelo menos foi isso que entendi ao entender a lógica.
Vamos tirar a dúvida na produção?
