### ISSUE TITLE
bug: ao sair do sistema com o usuário admin

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#75]
flow:
- editar curso
- minha área > sair

usuário: admin
analisar log

**Comment by moacirmoda** [comment]
Corrigido: Erro causado porque havia uma falha de segurança que permitia usuário não autenticado visualizar a página.

**Comment by intrepidocabral** [comment]
Tem um erro bastante frequente se repetindo que é o seguinte: quando um usuário admin está numa página de permissionamento restrito, se este clicar em "sair" o sistema deveria primeiro dar logout e depois jogar o user para home. Mas esse fluxo não está operando. Está caíndo na página de erro 500. 

Fluxo desejado: user logado como admin > qualquer página de acesso restrito (certificado, edição de curso, etc) > Minha área > sair > logout > home

Veja fluxo atual: user logado como admin > qualquer página de acesso restrito (certificado, edição de curso, etc) > Minha área > sair > logout > página de erro 500 "vc não tem permissão..." 

Veja erro em operação: https://youtu.be/6lvHfoQETHs

**Comment by moacirmoda** [comment]
Resolvido.
