### ISSUE TITLE
bug: adição de vídeo em unidade

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#77]
Quando tento adicionar um vídeo em uma unidade, mesmo preenchendo todos os campos, a aplicação dá bug e acusa preenchimento inconcluso. 

Veja comportamento do bug em:  https://youtu.be/lxPxCqbM600

**Comment by moacirmoda** [comment]
@robertkapa isso é porque não temos uma API do youtube configurada. Onde posso conseguir uma?

**Comment by intrepidocabral** [comment]
@moacirmoda não creio que seja isso... a mensagem de erro acusa que não foram preenchidos todos os campos... Parece problema relacionado com outra coisa. Antes, mesmo sem api, funcionava. De qualquer modo, vou criar duas chaves para api, com esses dois endereços, e mando as chaves no seu email, assim vc pode colocar no settings e ver se funciona.

**Comment by moacirmoda** [comment]
Corrigido. Realmente era problema da API. O sistema mandava que o atributo `name` fosse obrigatório, e como estavamos com erro na API, o vídeo era carregado, mas o nome não.
