### ISSUE TITLE
bug: input de número de horas de um curso não funciona

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#79]
Quando o admin ou professor estão montando um curso, não há opção na tela de edição do curso para inserir o número de horas do curso. Sem isso, o número de horas do curso no certificado fica travado. 

![selecao_071](https://cloud.githubusercontent.com/assets/641411/22156684/8b06ce76-df1b-11e6-90c1-54b971fbf85b.png)

**Comment by moacirmoda** [comment]
@robertkapa este campo é preenchido com o número de horas do curso no momento da criação do certificado.

**Comment by moacirmoda** [comment]
@robertkapa realmente, eu me confundi. Vou fazer.

**Comment by moacirmoda** [comment]
Criei um novo campo chamado __Total Hours__ (ainda será traduzido). Este campo é numérico e tem como default 0:
![image](https://cloud.githubusercontent.com/assets/549428/22799164/f24abc70-eeeb-11e6-81c1-806252c83d38.png)

Este campo agora é utilizado em todos os certificados.
