### ISSUE TITLE
bug: cabeçalho de static page do about com erro de chamada no menu mensagens

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#81]
![selecao_069](https://cloud.githubusercontent.com/assets/641411/22156756/e834ddb8-df1b-11e6-84fa-508ebb3bcfe1.png)

**Comment by moacirmoda** [comment]
Corrigido

![image](https://cloud.githubusercontent.com/assets/549428/22334500/2e7d2e10-e3c2-11e6-8561-da234471506d.png)
