### ISSUE TITLE
bug: forum

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#83]
Ref.: #29 
Na página de uma unidade, tentei inserir uma pergunta, mas não funcionou corretamente.

Ex.: http://if.dev.timtec.com.br/course/timfazciencia/lesson/aula-1
Tentei inserir a pergunta e clicar algumas vezes no enviar. Nada acontece:
![selecao_079](https://cloud.githubusercontent.com/assets/641411/22339120/1a92ed32-e3d0-11e6-9860-cffd6199b3cf.png)

Quando dei f5, a pargunta aparece repetidas vezes: 
![selecao_079](https://cloud.githubusercontent.com/assets/641411/22339164/3a95d838-e3d0-11e6-9d84-63d388452c9f.png)

**Comment by moacirmoda** [comment]
Resolvido.
