### ISSUE TITLE
botão "ver todos os cursos"

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#85]
Inserir botão "Ver todos" ao final da lista na home. O estilo pode ser igual ao "inscrever-se no curso".

Exemplo de estilo do botão (background vermelho, fonte branca):
![selecao_096](https://cloud.githubusercontent.com/assets/641411/22708016/db56be9c-ed5b-11e6-8261-73ff7ec1faff.png)

Exemplo de botão e de onde deve ficar: 
![selecao_095](https://cloud.githubusercontent.com/assets/641411/22707270/68caa57a-ed59-11e6-96c0-fcd0142cc80c.png)

Esse botão pode ser um link para a página "cursos" (http://timtec.dev.timtec.com.br/courses).

**Comment by moacirmoda** [comment]
Feito.
