### ISSUE TITLE
bug - links de materias adicionais quebrados

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#87]
![1b83dee0-d8e0-11e6-82f1-b56e528b83ce](https://cloud.githubusercontent.com/assets/641411/21901749/1b83dee0-d8e0-11e6-82f1-b56e528b83ce.png)

**Comment by moacirmoda** [comment]
@robertkapa parece que isso já era um bug antigamente. Veja como está em `mooc.timtec.com.br`:
![image](https://cloud.githubusercontent.com/assets/549428/22790704/3689e0a0-eece-11e6-9146-21c9246aba09.png)

Como prosseguimos? Imagino que teremos que trocar todo o sistema de markdown, pois pelo o que vi lib utilizada já é antiga.

**Comment by intrepidocabral** [comment]
resposta do @laurybueno sobre esse problema:

> nós não estamos mais usando markdown. Mudamos o editor desses conteúdos para TinyMCE e desabilitamos o sanitize para permitir embeds do youtube

**Comment by moacirmoda** [comment]
@robertkapa se optarmos por seguir pelo caminho de migrar para o TinyMCE teríamos que migrar todo o conteúdo existente. Penso que seja um grande trabalho.

**Comment by intrepidocabral** [comment]
@moacirmoda não precisamos migrar o editor. Precisamos apenas desabilitar o sanitize para que os links voltem a funcionar. É imprescindível que os links voltem porque tem mais de 20 cursos com esses links quebrados.

**Comment by moacirmoda** [comment]
Links voltaram a aparecer após desabilitar o Sanitize:
![image](https://cloud.githubusercontent.com/assets/549428/23103194/d8095ec8-f695-11e6-8d43-f3e3a8ccbd36.png)

Testado em: http://if.dev.timtec.com.br/course/html5/lesson/montando-a-estrutura-de-um-documento-html#/4

**Comment by intrepidocabral** [comment]
ok @moacirmoda ! Está funcionando os links para os materiais adicionais a partir dos cursos. Mas encontrei outro problema agora. 

Ao usar o mecanismo de upload de arquivos em "materiais adicionais" pela interface do angular, a aplicação faz o upload normalmente. No entanto, ao gerar o link para o arquivo, o caminho (path) fica sobreposto (path errado), impedindo que o usuário leigo (professor ou admin que estiver fazendo ou manipulando esses arquivos de upload) acesse e/ou linkem o arquivo corretamente. Antes não estava com esse erro. 

Exemplo de um link gerado erroneamente. Repare que a aplicação está duplicando o caminho (http://url/media): 

http://if.dev.timtec.com.br/media/http://if.dev.timtec.com.br/media/boas-praticas-em-desenvolimento-de-software/DSC00088.JPG

Veja vídeo demonstrando o comportamente erroneo na hora de acessar o link: 
https://youtu.be/_53P0HOL-xg

**Comment by moacirmoda** [comment]
Resolvido.
