### ISSUE TITLE
bug: títulos dos cursos com tamanho quebrado

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#89]
Na **página do profile** (http://url/profile/), os boxes com os cursos aparecem quebrados. É necessário diminuir a fonte do título para que não fique quebrado. 

Veja como está: 
![selecao_022](https://cloud.githubusercontent.com/assets/641411/22704342/87ed7456-ed4e-11e6-898f-a6be7ffde468.png)

Como deveria ser (repare que eu diminuí o tamanho da fonte para exemplificar.): 
![selecao_020](https://cloud.githubusercontent.com/assets/641411/22704348/8c0f5a5e-ed4e-11e6-88d8-379a19c1533c.png)

**Comment by moacirmoda** [comment]
Corrigido.

**Comment by intrepidocabral** [comment]
Acabei de testar e o problema persiste. Limpei o cache e testei no ambiente de testes com tema timtec e os títulos continuam gigantes na página de profile. @moacirmoda vc chegou a gerar os assets de novo? 

![selecao_034](https://cloud.githubusercontent.com/assets/641411/23105763/0f118562-f6c3-11e6-935d-eec4d9bd0164.png)

**Comment by moacirmoda** [comment]
@robertkapa eu testei aqui numa aba anônima e correu normalmente, veja:

![image](https://cloud.githubusercontent.com/assets/549428/23168470/0538d684-f827-11e6-8e5d-1dc64928508b.png)

**Comment by intrepidocabral** [comment]
@moacirmoda vc está olhando na página e no estilo errado. O problema que reportei acontece na página do profile e não em meus cursos. Veja: 

http://timtec.dev.timtec.com.br/profile/

**Comment by intrepidocabral** [comment]
@moacirmoda poderia fazer esse item para fazermos logo o release?

**Comment by moacirmoda** [comment]
Resolvido

**Comment by intrepidocabral** [comment]
ok! vou testar.
