### ISSUE TITLE
bug - botão de download do certificado não funciona

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#90]
![selecao_023](https://cloud.githubusercontent.com/assets/641411/22705388/7be4a004-ed52-11e6-882f-c45fba621179.png)

![selecao_026](https://cloud.githubusercontent.com/assets/641411/22706271/c5adb222-ed55-11e6-9f86-9786dade1dbd.png)

**Comment by intrepidocabral** [comment]
O bug tinha sido resolvido e voltou a aparecer. Ver #80

**Comment by moacirmoda** [comment]
@robertkapa me dá um exemplo específico, com link pra eu poder testar.

**Comment by intrepidocabral** [comment]
Exemplo: 
http://timtec.dev.timtec.com.br/certificate/rCIt83N6
http://if.dev.timtec.com.br/certificate/NQC-ibpK/

Veja comportamento com erro: 
 https://youtu.be/JObevtxd0qk

**Comment by moacirmoda** [comment]
@robertkapa debuguei e vi que nos ambientes que temos de homologação não estava instalado a lib selenium. Adicionei no requirements e nos links que vc mandou voltaram a funcionar os downloads. Acho válido testarmos em mais certificados. Nos que eu testei, todos seguiram com sucesso, em ambos os temas.

**Comment by intrepidocabral** [comment]
ok @moacirmoda ! 

Acabei de testar e vi que está ótimo, tanto no desktop quanto no responsivo. No entanto tive um problema(bug) no tema dos ifs. O certificado está sendo gerado com erro, há uma margem grande a esquerda e a direita aparece comido (certificado com um pedaço cortado). Isso está acontecendo apenas no tema dos ifs, no tema timtec está tudo certo. Veja:
[NQC-ibpK19Feb2017.pdf](https://github.com/institutotim/timtec/files/786115/NQC-ibpK19Feb2017.pdf)

![selecao_033](https://cloud.githubusercontent.com/assets/641411/23105727/4fd6f844-f6c2-11e6-9eef-be17e7f6fe2e.png)

**Comment by moacirmoda** [comment]
@robertkapa fiz alguns ajustes e creio que resolveu. Acho bom dar uma testada maior.
