### ISSUE TITLE
bug - no tema timtec, traduzir botão e menções a "meus certificados"

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#91]
![selecao_021](https://cloud.githubusercontent.com/assets/641411/22705684/b2133d60-ed53-11e6-881d-a63af3a628a4.png)

![selecao_024](https://cloud.githubusercontent.com/assets/641411/22705693/b9c12b44-ed53-11e6-916d-faccff9775ab.png)

**Comment by moacirmoda** [comment]
Criado diretório de traduções no tema timtec.

**Comment by intrepidocabral** [comment]
acabei de verificar e continua sem tradução.

**Comment by moacirmoda** [comment]
Resolvido:
![image](https://cloud.githubusercontent.com/assets/549428/23103594/05808880-f69c-11e6-8f5c-40426006aa85.png)

O problema estava no package, que não estava pegando o diretório locale do repositório do tema, e também o Django não compila locales de terceiros, então tive que adicionar o compilado também.
