### ISSUE TITLE
BUG: no tema timtec, retirar menção a "Certificados". Substituir por "Comprovantes"

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#95]
no tema timtec, substituir a palavra certificados por comprovantes

![selecao_011](https://cloud.githubusercontent.com/assets/641411/24315064/b5eb70d6-10c3-11e7-967f-c565a28071b6.png)

![selecao_013](https://cloud.githubusercontent.com/assets/641411/24315106/fa875570-10c3-11e7-9fa5-2944a03b15a5.png)

![selecao_014](https://cloud.githubusercontent.com/assets/641411/24315110/fe3efe3e-10c3-11e7-8187-e41276d9c3da.png)

**Comment by Nathlis** [comment]
Tema TIM Tec o nome "comprovante" está escrito errado.

![tim tec](https://cloud.githubusercontent.com/assets/18741130/25129371/203b4782-2414-11e7-860c-749f5e916647.png)

**Comment by moacirmoda** [comment]
kkkkk vazou um debug. Vou arrumar.

**Comment by intrepidocabral** [comment]
> kkkkk vazou um debug. Vou arrumar.

Foi o @GustavoVS que fez isso. Já pegamos ontem e ele já corrigiu! Valeu @moacirmoda hahaha

**Comment by moacirmoda** [comment]
ah ta kkk blz..
