### ISSUE TITLE
BUG: biografia de professores não aparece na home individual dos cursos

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#96]
Comportamento esperado:
![download 2](https://cloud.githubusercontent.com/assets/641411/24315326/2aee4952-10c5-11e7-93f8-0b7abafcd3d5.png)

Como está:
![download 1](https://cloud.githubusercontent.com/assets/641411/24315277/ed160f2a-10c4-11e7-93ca-660c5ff57e1f.png)

**Comment by moacirmoda** [comment]
Corrigido:

![image](https://cloud.githubusercontent.com/assets/549428/24471738/6cee955a-1499-11e7-8209-74937969da87.png)


![image](https://cloud.githubusercontent.com/assets/549428/24471740/6faa3b64-1499-11e7-8717-e472eda99477.png)

**Comment by intrepidocabral** [comment]
testado a aprovado.
