### ISSUE TITLE
BUG: na página de todos os cursos, nomes dos professores não aparece

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#97]
Comportamento esperado:
![download 3](https://cloud.githubusercontent.com/assets/641411/24315502/2d71b1cc-10c6-11e7-908a-159ab3070700.png)

Como está: 
![selecao_015](https://cloud.githubusercontent.com/assets/641411/24315499/1ee5b7ac-10c6-11e7-833d-d61d6addc36c.png)

**Comment by moacirmoda** [comment]
Corrigido:
![image](https://cloud.githubusercontent.com/assets/549428/24471457/8aeabd8c-1498-11e7-86e8-95857886042d.png)

![image](https://cloud.githubusercontent.com/assets/549428/24471489/9d4c7222-1498-11e7-9610-980672747712.png)


PS: Há cursos sem professor registrado, por isso não aparecem os nomes.

**Comment by Nathlis** [comment]
Como assim tem professores não registrados? Até onde sei todos estão.

**Comment by moacirmoda** [comment]
Por algum motivo, que precisa ser investigado, a massa de dados utilizada neste teste possui alguns cursos sem professor. @GustavoVS vc pode me dar uma ajuda nisso?

**Comment by moacirmoda** [comment]
Analisar se o problema pode corresponder aos cursos com professores que não possuem usuário registrado na plataforma.

**Comment by moacirmoda** [comment]
Resolvido.

**Comment by intrepidocabral** [comment]
Esses problemas está nos 2 temas. 

**PROBLEMA 1:**  Problema persiste na página geral de cursos do tema dos ifs: 
Comportamento esperado (logado ou não logado):
![selecao_039](https://cloud.githubusercontent.com/assets/641411/24681810/33a37670-196d-11e7-86e2-74cb53ce89d9.png)

**Como está:** 
![selecao_038](https://cloud.githubusercontent.com/assets/641411/24681806/302ff770-196d-11e7-96f0-2126a88eacba.png)

**PROBLEMA 2:** 
Nas internas o nome dos professores continua faltando. 

Comportamento esperado(logado ou deslogado http://cursos.timtec.com.br):
![selecao_041](https://cloud.githubusercontent.com/assets/641411/24681970/d38ecb58-196d-11e7-808e-cb424d99ec02.png)

**Como está:** 
![selecao_040](https://cloud.githubusercontent.com/assets/641411/24681973/d7b1e1de-196d-11e7-8ee5-82ab23109da2.png)


**PROBLEMA 3: HOME DO CURSO** 
O nome do professor sumiu.

Comportamento esperado:
![selecao_042](https://cloud.githubusercontent.com/assets/641411/24682160/a75b7760-196e-11e7-9681-974db9d789a2.png)

Comportamento como está: 
![selecao_043](https://cloud.githubusercontent.com/assets/641411/24682163/ab3dffce-196e-11e7-8a0d-2c48eeff14dc.png)

**Comment by moacirmoda** [comment]
Resolvido.

**Comment by intrepidocabral** [comment]
ótimo!
