### ISSUE TITLE
BUG: imagem de fundo (background) trocada no tema timtec

### ISSUE THREAD

**Issue by intrepidocabral** [institutotim/timtec#98]
Comportamente esperado:
http://cursos.timtec.com.br/static/img/illustrations/home-m.d5d16203f615.png

Como está:
http://li1109-208.members.linode.com/static/img/illustrations/home-m.png?7ef5b09c26e9

**Comment by moacirmoda** [comment]
Corrigido:

![image](https://cloud.githubusercontent.com/assets/549428/24472001/817ea162-149a-11e7-852b-c261a7b50a3c.png)

**Comment by intrepidocabral** [comment]
Vc mudou apenas a imagem para resolução média, tinha que mudar também a imagem para resolução grande (large). Mas eu estou aqui com Gustavo e já mudamos a large, então estou fechando a issue.
